### ISSUE TITLE
Adding a fallback for potentially missing X database variables

### ISSUE THREAD

**Issue by Elv13** [elenapan/dotfiles#1]
https://github.com/elenapan/dotfiles/blob/3b857495fbeb072e3f4899aafc9d4a770aa5f8ab/config/awesome/themes/manta/theme.lua#L176

Hello, sorry to bother you,

As reported on r/unixporn by "ryuuji89", this can cause error on systems where the X database is empty. To mitigate this and for general portability, it is recommended to add `xrdb.color8 or "#ff0000"` for all `xrdb` variables.

**Comment by elenapan** [comment]
Woops, sorry for the delay, didn't even notice I had issues in here.
I updated the theme so that it uses the exact same fallback colors as in my screenshot.
Thank you for informing me.
