### ISSUE TITLE
[Ephemeral] Few Issues/questions

### ISSUE THREAD

**Issue by Hkyx** [elenapan/dotfiles#102]
Hi @elenapan  !

Thanks you for the good work :)
I'm trying Ephemeral theme and want to make some changes, but need your help :)
- How do you manage the background of the icon in the bottom right ? like if I change the order of the icons in the bottom right I need to change the background too to keep the gradient between them
- [Bug] Notifications seems to get some bug, the ui is sometime stuck when I receive from chrome one or more notifications, when it came, I need to reload awesome itself
- I usually use the-glorious-dotfiles which use account lock system. the advantage is to not hardcode a password when we lock our screen, do you know how it's possible to import it into ephemeral ?

thanks, hk

**Comment by elenapan** [comment]
Hi there,

- Inside `~/.config/awesome/elemental/bar/ephemeral.lua`, look for the lines that run the `create_button()` function.

   For example:
   
   ```lua
   local exit = create_button("", x.color6, x.color8.."C0",x.color8.."E0")
   -- ...
   local volume = create_button(volume_symbol, volume_unmuted_color, x.color8.."30", x.color8.."50")
   -- ...
   local microphone = create_button(microphone_symbol, microphone_unmuted_color, x.color8.."60", x.color8.."80")
   -- ...
   local music = create_button("", x.color4, x.color8.."90", x.color8.."B0")
   ```
   
   The third and fourth arguments of the function determine the background color and the hover background color.
   
   I am using `x.color8` as a base color, which usually represents the `grey` color in terminal colorschemes.
   
   You can use the RGBA format to add transparency to any color in AwesomeWM. This is why I am adding strings like `"C0"` or `"30"` to the end of the `x.color8` string. If you want to change the order of them, or add your own, you need to change the transparency of `x.color8` inside `create_button()` accordingly.
   
   Here is a transparency guide so you know which hexcode to use for a specific transparency level:
   
   <details>
     <summary>Hexcode transparency guide</summary>
   
       100% — FF
       95%  — F2
       90%  — E6
       85%  — D9
       80%  — CC
       75%  — BF
       70%  — B3
       65%  — A6
       60%  — 99
       55%  — 8C
       50%  — 80
       45%  — 73
       40%  — 66
       35%  — 59
       30%  — 4D
       25%  — 40
       20%  — 33
       15%  — 26
       10%  — 1A
       5%   — 0D
       0%   — 00
   </details>

- Chrome notifications: I do not use Chrome so I cannot debug this, but could you check if it works with the default AwesomeWM config?

- Lock screen without hardcoded password: Yes it is possible. See [this wiki article](https://github.com/elenapan/dotfiles/wiki/Advanced-setup#pam-authentication-through-the-awesomewm-login-screen) on how to set it up.

**Comment by Hkyx** [comment]
Thank for you reply ! :)
- Ok I mised the Hexa code when I tried :) works perfectly now ! 
- Ok but is it a easy way to do that ?
- thank I'll check that ! :)

**Comment by elenapan** [comment]
The simplest way is to temporarily rename your `~/.config/awesome` folder to something else, and log in with Awesome.
It should then use the default config.

You can use `mod+r` to open a prompt and run Chrome from there.

**Comment by Hkyx** [comment]
ok, with a default config of awesome or another one like glorious-dotfiles, it's working correctly.
also, the settings button seems not working when I clic on it.

**Comment by elenapan** [comment]
> ok, with a default config of awesome or another one like glorious-dotfiles, it's working correctly.

Alright then, I will investigate and try to fix it soon.

> also, the settings button seems not working when I clic on it.

I use that button to reload the AwesomeWM configuration whenever I make changes to it. It does the same as <kbd>super + shift + r</kbd>.

**Comment by Hkyx** [comment]
[udpate] It seems the notifications get the same issues with slack notifications, but teams does not.
The difference is teams don't have the same rules/styling than the others

**Comment by elenapan** [comment]
> It seems the notifications get the same issues with slack notifications, but teams does not.

This is probably because Teams uses its own method of spawning notifications which does not go through AwesomeWM.

---

Regarding the issue, I could not reproduce it on Google Chrome (or any other browser that is). I was running Slack in a tab, allowed desktop notifications, and they showed up fine without making the WM freeze.

1. Have you tried any other notification theme except `ephemeral`? Is the issue still there?

   https://github.com/elenapan/dotfiles/blob/5450eb54706348fdb570ec749e54aa19f5595c76/config/awesome/rc.lua#L50-L55

2. Could you provide some AwesomeWM logs when the freezing happens?

   You can install Xephyr (in most distros the package is called `xorg-xephyr` or `xserver-xephyr`)
   and run in a terminal:
   ```shell
   Xephyr :1 -screen 1366x768 &
   DISPLAY=:1 awesome
   ```

   This will start awesome in a separate window. I would like you to paste the output from that terminal here after the freeze happens.

**Comment by Hkyx** [comment]
I;ll try theses option and come back after :)

**Comment by Hkyx** [comment]
tried the others themes, it's working better but still get some freeze, I'll be outside for two week without my laptop, I'll try the Xephyr when I'm back :)

**Comment by Hkyx** [comment]
Hi :) 
some late but I changed all the notifications systems and it's working but I didn't use zephyr for the debug

**Comment by elenapan** [comment]
Alright. So if the freezes are gone I think we can consider this issue resolved.
Let me know if the problem comes back.
