### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by otavioschwanck** [elenapan/dotfiles#103]
Tested on Ubuntu and Arch.

Awesome 4.3

![2020-08-09_02-35](https://user-images.githubusercontent.com/9551316/89725775-6bf44780-d9e9-11ea-8b4b-450a4ae20642.png)

**Comment by elenapan** [comment]
Hi there,

It is stated in the [Setup](https://github.com/elenapan/dotfiles#setup) section of the README that the [git version of AwesomeWM](https://github.com/awesomeWM/awesome/) should be installed.

Awesome v4.3 is too old and my configuration uses features that are only available in the git version.

**Comment by elenapan** [comment]
Closing as the issue should be solved by installing `awesome-git`.
