### ISSUE TITLE
How are your fonts so beautiful?

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#105]
I copied your fonts-config and i have antia-aliased and all this stuff. I even tested it with your own fonts on the setup. (As let's say, Source Sans Pro for the sans-serif), but my fonts are not beautiful like this:

![2020-08-12_23-44](https://user-images.githubusercontent.com/17055027/90088662-da8d1a00-dcf5-11ea-9278-822c0fce8e7a.png)

Is actually not NEARLY close. Look here at my tasklist: 

![2020-08-12_23-55](https://user-images.githubusercontent.com/17055027/90089260-402dd600-dcf7-11ea-825e-0de402ae2962.png)

Is there anything more you do with the fonts?

**Update: I updated the second screenshot**

**Comment by elenapan** [comment]
Oh. I think it is just because of my HiDPI monitor.
More pixels -> more detail -> smoother fonts.

If you check the themes I released on my old laptop, e.g. [Lovelace](https://github.com/elenapan/dotfiles/wiki/Gallery#lovelace), the fonts do not look nearly as good as now.

**Comment by hrqmonteiro** [comment]
You mean the apple monitor, though?

So, i have a laptop on Full Hd and a PC on a 4k monitor, and the fonts are pretty shit on them, too, so there's nothing a can do except buy a Apple Monitor? That's sad hahaha

**Comment by elenapan** [comment]
It is not an Apple monitor (although they are pretty good).

I am using a 15.6 inch laptop monitor with a resolution of `3840x2160`. As a result, I have to set `Xft.dpi: 288` in my `~/.Xresources` in order for things to be scaled correctly. Without this setting, fonts and AwesomeWM elements look tiny.

All that matters for having smooth fonts is pixel density (basically a high DPI). It could be that your monitor is so large that even with a 4K resolution, pixels are not as dense as on my much smaller monitor.

**Comment by hrqmonteiro** [comment]
Well i guess it could be that. I'm running 166 Dpi, so probably not even close of the quality.

But just one few quick question: i'm using Google Sans as you said you use for the sans. And on your config, on the ephemeral bar for example, you use "sans medium 11", but looking at the prints i sent, your font looks "thicker" than me, as in the font weight are higher. So, even without the dpi question, shouldn't my font be thicker, more like yours, even though in low quality? I set my font as Google Sans Medium and still looks thinner..

![2020-08-12_23-44](https://user-images.githubusercontent.com/17055027/90343100-e45b9980-dfe3-11ea-9d51-0b2f1aaa09fe.png)
![2020-08-16_17-14](https://user-images.githubusercontent.com/17055027/90343104-ec1b3e00-dfe3-11ea-98df-c69063445c77.png)

**Comment by elenapan** [comment]
Yes, the `medium` variant should be slightly thicker than normal.

It could be that you have installed Google Sans but not its `medium` variant.

You can use this command to make sure it is installed:

```shell
fc-list | grep 'Google Sans Medium'
```

It should print at least 1 line.
For example, this is my output:

```
/home/elena/.local/share/fonts/Google-Sans-Font/GoogleSans-Medium.ttf: Google Sans,Google Sans Medium:style=Medium,Regular
/home/elena/.local/share/fonts/Google-Sans-Font/GoogleSans-MediumItalic.ttf: Google Sans,Google Sans Medium:style=Medium Italic,Italic
```

**Comment by hrqmonteiro** [comment]
I had it, but it was some issue with the width on my setup, but i could work it out. And sorry for late comment and keeping the issue closed, it was just that i was frustrated with my config and stop working on it haha.
