### ISSUE TITLE
Alacritty as floating_terminal

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#106]
Hi, Elena, sorry for bothering you for like, 1000th time, but do you know if is it possible to set alacritty for the "floating_terminal" and it work properly?

I tried setting urxvt and st and it is ok, but my terminal of use for two years is alacritty, and no matter what i do, it doesn't work as the floating hotkey, it always opens fullscreen. And if i change no code other than the "floating_terminal" instance, every other terminal works. So, do you know if it is not possible to set a hotkey to open Alacritty in floating property?

**Comment by elenapan** [comment]
You should set `floating_terminal = "alacritty --class floating_terminal"`

This is because some terminals (like Alacritty), do not support being spawned with extra properties. Thus I had to set a window rule that makes all terminals with instance name `floating_terminal` to be floating.

**Comment by snitxmhm** [comment]
Hi, Elena. I set `floating_terminal = "st -c floating_terminal"`.And `xprop` shows `WM_CLASS(STRING) = "st-256color", "floating_termianl"`.But st still can't floating.

**Comment by hrqmonteiro** [comment]
It worked now! Thanks!

Also, thanks for all the issues i've opened in these months @elenapan. Unfortunately i'm quitting awesome haha, i give up, i simply can't learn it. I've been trying for 8 months and accomplished nothing. Then i tried just to use your config as a base and edit, but it doesn't work too. I gave up haha. I even tried to take a course on lua syntax to see if i could apply on awesome but it doesn't fit.

I'm saying all of this just to say that you are simply AWESOME, never seen someone this awesome in Linux configs. Keep rocking, you are amazing! Congratulations!
