### ISSUE TITLE
Is microphone_overlay_toggle() code missing ?

### ISSUE THREAD

**Issue by GitHubRandom** [elenapan/dotfiles#107]
Hi,
First of all, your work is awesome.
Second thing, I noticed that there is a keybinding for a microphone overlay but it's not working. It's calling microphone_overlay_toggle function that does not exist. Am I missing something ?
Last thing, your work is awesome :)

**Comment by elenapan** [comment]
Commit 2e143eff4fbd5f5b4f8c217a0f3e6104235a9408 has added the microphone overlay.
The keybind to toggle it remains the same: <kbd>super + shift + v</kbd>
