### ISSUE TITLE
Button on music player not working

### ISSUE THREAD

**Issue by Azaleahart** [elenapan/dotfiles#112]
Hi, hope I'm not bothering you with this issue
the problem is when I use ncmpcpp with alacritty or kitty the shortcut button is working but it's not working when I use termite.
when I launch it manually on terminal with `--class music_player -e ncmpcpp` kitty gives this output
`[248 20:24:05.640384] [PARSE ERROR] Unknown CSI s sequence with start and end modifiers: '?' '' and 1 parameters`
while alacritty and termite gives no output.
Is there anything I can do to fix this?

Cheers,
Fahreza

**Comment by elenapan** [comment]
Hi there,

I just tried `termite --class music -e ncmpcpp` in the terminal and it worked on my side.

Does setting `music_client` to that value work?

```diff
diff --git a/config/awesome/rc.lua b/config/awesome/rc.lua
index d25f47c..95561f8 100644
--- a/config/awesome/rc.lua
+++ b/config/awesome/rc.lua
@@ -82,7 +82,7 @@ user = {
     file_manager = "kitty -1 --class files -e ranger",
     editor = "kitty -1 --class editor -e vim",
     email_client = "kitty -1 --class email -e neomutt",
-    music_client = "kitty -o font_size=12 --class music -e ncmpcpp",
+    music_client = "termite --class music -e ncmpcpp",

     -- >> Web Search <<
     web_search_cmd = "xdg-open https://duckduckgo.com/?q=",
```

**Comment by Azaleahart** [comment]
I did use that value for the music player, and it didn't work. 
The only button that work is play, next, previous, toggle sidebar & notification, randomize, and repeat.

**Comment by elenapan** [comment]
Oh I see. Now I understand the problem.

The first four buttons on the music player's sidebar work by sending fake keys to `ncmpcpp` with `xdotool`. I forgot to include `xdotool` in the dependencies.

Please install `xdotool` and let me know if the buttons work.

**Comment by Azaleahart** [comment]
I'm sorry if my english confused you.

As I mentioned earlier I the buttons including the four using `xdotool` works perfectly when I used `alacritty` or `kitty`, so I believe it's not a dependencies problem.

My `termite` doesn't use any special config either, just plain old `termite` with the font and colorscheme changed.

**Comment by elenapan** [comment]
Alright. I managed to reproduce this bug with `termite`.

I also did some digging and found this relevant issue:
https://github.com/thestinger/termite/issues/167

Unfortunately, I cannot do anything about this except suggest setting a different terminal just for the music client command. Of course, you can still keep using `termite` for all other purposes.

**Comment by Azaleahart** [comment]
I guess I'll use different terminal for the music client, thanks for your help.
