### ISSUE TITLE
picom invalid blur method kawase ?

### ISSUE THREAD

**Issue by notKamui** [elenapan/dotfiles#113]
Hi, sorry if this sounds dumb, I actually never used picom so I'm a bit at a loss. After checking on the internet some information about this, I couldn't find something that answers my question.

When I launch picom with your config (as a deamon or not), I have the following error
```
[ 09/06/2020 17:01:58.845 parse_config_libconfig FATAL ERROR ] Invalid blur method kawase
[ 09/06/2020 17:01:58.845 main FATAL ERROR ] Failed to create new session.
```

Are you using a specific fork of picom perhaps, or did I misunderstood something ?

Btw your whole config is really amazing and _awesome_ !

**Comment by elenapan** [comment]
Hi there, thank you for your kind words.

Indeed, I am using [this specific fork of picom](https://github.com/ibhagwan/picom), which combines the very strong `kawase` blur and anti-aliased rounded corners.

**Comment by notKamui** [comment]
Thank you very much !
