### ISSUE TITLE
VSCode Theme

### ISSUE THREAD

**Issue by mtxr** [elenapan/dotfiles#12]
Hi, 

With the colors you're using, I believe you could create a great VSCode theme.

Do you plan to do it?

Great job btw. I'm enjoying a lot

Thanks!

**Comment by elenapan** [comment]
Hello,
As of now I am using a different editor so I probably won't create a VSCode theme.
Also, correct me if I am wrong, but I think VSCode uses TextMate format (`.tmTheme` files) for colorschemes, just like Sublime Text.
I uploaded the `.tmTheme` I am using [here](https://pastebin.com/Wd022ZP1). You could check if it works for you.

**Comment by mtxr** [comment]
Thanks!

Is it ok if I publish it and credit it to you?

I've been publishing extensions for more than 2 years, I believe this theme would be a great addition.

**Comment by elenapan** [comment]
Sure, go ahead!
