### ISSUE TITLE
font issue - typicons icons not appearing in terminal

### ISSUE THREAD

**Issue by EllatharTheHalfling** [elenapan/dotfiles#121]
I'm back again with another slight issue that's really only a minor inconvenience. This time with something that was working prior (at least, was working after a file change), unfortunately that's no longer the case.

Kitty appearance shown with bunnyfetch:
![2020 10 19-19 35 17 screenshot](https://user-images.githubusercontent.com/67206562/96533348-9ad93600-1242-11eb-90a8-355e1fa1f673.png)

Kitty.conf relevant section:
```
# Fonts
font_family      monospace
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        10.0
```

fontconfig:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <!-- set monospace font -->
    <match target="pattern">
        <test qual="any" name="family"><string>monospace</string></test>
        <edit name="family" mode="assign" binding="same">
            <string>Iosevka Custom</string>
            <string>Typicons</string>
            <string>icomoon</string>
            <string>Material Icons</string>
            <string>Noto Color Emoji</string>
        </edit>
    </match>
</fontconfig>
```

**Comment by elenapan** [comment]
Hi there,

The `kitty` font configuration seems good to me.
The only difference I see with my setup is in your `fontconfig` section.

```diff
- <edit name="family" mode="assign" binding="same">
+ <edit name="family" mode="prepend" binding="strong">
```

Could you try this and let me know?

**Comment by EllatharTheHalfling** [comment]
Nothing changed with that edit.
For now what I've done, for the sake of appearance, is use icons that I've copy/pasted into the `bunnyfetch` script from a document editor, using the FontAwesome icons and also changing the fonts.conf file to search for `Font Awesome` instead of `Typicons`.

It works for now, however I"m not sure if that's necessarily a fix and I am willing to continue trying as I do have backups of the original `font.conf` and `bunnyfetch`.

Something I forgot to mention is I'm currently on Ubuntu 19.10, so my current guess (given that searching for Font Awesome and using the icons copied from a document editor into the script does work) is that the OS is reading and displaying the font differently? this could very well also be a case of so many fonts in the system that the original icons that were intended to be there are being displayed using a different monospace font.

**Comment by EllatharTheHalfling** [comment]
Hey Lena,

Just wanting to update you on what I've found in my searching.

I installed another font labelled `Typicons` (where the font was searchable in a document editor as Typicons instead of `Font Awesome`)

using this font I was able to see the icons from typicons just fine, though the caveat here is that the symbols expected still isn't what is shown and they do need to be replaced either way, but this would simply be copy/pasting the symbols themselves from a document editor into bunnyfetch rather than doing that and editing `fonts.conf`.

Anyway, this is leading me to believe that for those on `ubuntu` (and possibly other `debian` based systems) the font provided gets installed as Font Awesome Regular, not Typicons, and therefore `fonts.conf` needs to reflect this differentiation.

where I happened upon the other font file that allowed me to use the original font.conf file is the following location
[https://materialsproject.org/static/fonts/typicons/](url)

If you'd like I can at least provide the updated `bunnyfetch` and `fonts.conf` to show your intended glyphs (since I had chosen to change mine since I was in there anyway) and it could possibly be added in as a variant for those that might be in the same situation (though I imagine this is rare as from what i've seen few people use a WM on top of base ubuntu)

**Comment by elenapan** [comment]
Hi there, thank you very much for the update.

I was not aware that Typicons are now included in Font Awesome. You are right that, in this case, the font family should not be set as `Typicons` inside `fonts.conf`.

Regarding your issue with the stand-alone Typicons font, it could be that various updates to the font may have caused some glyphs to be displaced, so people who are using newer versions than me get different glyphs than the ones I intended.

In that case, have you tried the Typicons font uploaded [on my dropbox](https://www.dropbox.com/s/x89j0sycuas0v9w/typicons.ttf?dl=0)? It is an older version which I have been using for more than a year and the `bunnyfetch` glyphs should render correctly with it.

Of course, I would also appreciate it if you you could post your updated `bunnyfetch` and `fonts.conf`. I will be redirecting anyone who has the same issue to your answer here. Thank you again!

**Comment by EllatharTheHalfling** [comment]
Sorry for the delay. I did try the Typicons font in your dropbox and it didn't resolve the issue.

There is another issue that I did notice, however. in that the icons will have colored blocks after them, seems to be reading the space as a character with typicons. I haven't found a fix for this and will continue looking in my spare time because it's an issue that i did have with the previous versions of all this. For this reason I really suggest the `Font Awesome` folder in the upload as it's the cleanest option. Have some other issues I've noticed and what I'll probably end up doing is making a bunch of variants to better work on 19.10 especially since these wouldn't just apply to me, but those with Pop!_OS as well. 

So anyway here's the files.
https://github.com/EllatharTheHalfling/Dotfile-variants/tree/main/Lena%20Variants

**Comment by EllatharTheHalfling** [comment]
Hey Lena,

Wanted to give a bit of news that may change things:
I had a system failure that required a reinstall and rather than restore from a backup I chose to start over as there were some issues that plagued the system as well as some optimizations that I needed to make anyway. There is a chance the above becomes null due to some errors that were on the original install that are no longer present, so if we could keep this open for the time being until I know for sure. I should have everything finished by this weekend.

**Comment by EllatharTheHalfling** [comment]
came to give a small update:
this is gonna take longer than the weekend.
now it's not working at all, regardless of which font I use. not quite sure what's causing the issue this time.
this is what i'm seeing now regardless of which font i've tried.
![2020 11 07-15 59 11 screenshot](https://user-images.githubusercontent.com/67206562/98453823-48d55300-2112-11eb-8f6a-90acd4b3d453.png)

however, i'm also noticing that the devicons plugin for ranger produces the same lines
![2020 11 07-16 00 50 screenshot](https://user-images.githubusercontent.com/67206562/98453836-7a4e1e80-2112-11eb-88f7-10445181ea35.png)

so i'm going to continue to look into this. i'm really starting to think that the system parses fonts differently, so once i have a definitive answer i'll update you.

i'll leave it up to you whether you want to close this issue or leave it open in hopes of someone else coming in and offering some insight

**Comment by elenapan** [comment]
Oh hey, sorry for the delay, I did not get notifications for your edits.

- From Kitty's help page:
   ```
   --single-instance, -1
     If specified only a single instance of kitty will run. New invocations
     will instead create a new top-level window in the existing kitty
     instance. This allows kitty to share a single sprite cache on the GPU
     and also reduces startup time. You can also have separate groups of
     kitty instances by using the --instance-group option
   ```
   
   I have also found out that when zooming in/out with <kbd>ctrl+shift+=</kbd> and <kbd>ctrl+shift+-</kbd>, all the terminals that belong in the same instance zoom as well.
   Lastly, this also means that these terminals share font settings: If you want to do font tests while using `kitty -1`, you need to make sure that **all** the other kitties launched with `-1` close first, or the new font settings will not be loaded.
   The safest bet while trying to solve this issue is to use `kitty`.

- According to `gucharmap`, that squiggly heart in your **EDIT 2** is a FontAwesome glyph.
   ![image](https://user-images.githubusercontent.com/31134749/99154897-08e71080-26bc-11eb-9924-c53111afd5a5.png)

---

Finally, I very much appreciate that you are going the extra mile by explaining what you are doing. I do not mind keeping the issue open. You are free to close it whenever you feel like the issue is resolved.

**Comment by EllatharTheHalfling** [comment]
Alright, well I still want to try to figure out a way to keep things without editing your dotfiles too much on ubuntu if possible.
and yeah the heartbeat icon is a font awesome icon, but the regular heart is not strictly fontawesome and it would turn into a weird blob. pretty sure that's caused by multiple fonts using the same unicode character code and there's really no way around that other than specifying the exact font you want to load.

I'll keep it open for a few more days, if I still can't find a fix that is definitive I'll unfortunately have to consider this a problem that people on certain versions of ubuntu will have to sort out themselves. It's not too hard to do so, just frustrating (especially if you don't know where to start).

Lastly, I enjoy going through the extra effort of trying to explain things the best I can. I often find myself in git issue trackers if I have an issue and nothing bothers me more than seeing someone figure something out, but not share how, and then by the time I, or someone else, find it and go to ask, it's been months or years and they've forgotten how.

**Comment by EllatharTheHalfling** [comment]
Alright so, I'll be closing with this comment, but basically to sum up everything so far:

Ubuntu puts fontconfig in `~/.config/fontconfig/fonts.conf`
 - however Kitty will actually still try to read from `~/.fontconfig/fonts.conf` and cause problems between running kitty normally and in single instance.

The fonts installed at this point are:
`typicons.ttf` (which is installed as Font Awesome) from the dotfiles here and `fontawesome.ttf` which is Font Awesome 4.7.0 from [gabrielelana's repo for terminal awesome fonts](https://github.com/gabrielelana/awesome-terminal-fonts). the font.conf configuration is currently as follows:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <!-- set monospace font -->
    <match target="pattern">
        <test qual="any" name="family"><string>monospace</string></test>
        <edit name="family" mode="assign" binding="same">
            <string>Iosevka Custom</string>
            <string>FontAwesome</string>
            <string>icomoon</string>
            <string>Material Icons</string>
            <string>Noto Color Emoji</string> 
        </edit>
    </match>
</fontconfig>
```

Bunnyfetch does need to be edited after installing fonts to use unicode characters that the user finds as I've now run into 5 different occasions where characters change places to prevent conflict where possible. bothersome, but it's the way it is it seems. At least on Ubuntu 19.10 (Won't be able to test on 20.04 until particular setup is viable to move over)

In the event that the person is using both these and the ranger devicons plugin, `ranger` needs to be loaded in kitty.launched without the single-instance flag otherwise there are conflicts with devicons where they will sometimes show and sometimes not, either way the `fontawesome` characters that would normally overlap with `devicons` will be given priority if `~/.config/fontconfig/fonts.conf` has the fontawesome font designated in it.

no other conflicts to note as of this time.

I will be adding these files to the variant dotfiles I've uploaded previously which can be found [here](https://github.com/EllatharTheHalfling/Dotfile-variants/tree/main/Lena%20Variants) in hopes that at least one of them helps someone. But I cannot create files for every possible instance (nor do I want to try) and so it's a lot of tinkering to be done.

This has honestly been an experience and while I'm starting to regret using Ubuntu more and more each day I can't really say i don't enjoy the challenges I've been met with.
