### ISSUE TITLE
error during startup! attempt to call a nil value (field 'connect_signal')

### ISSUE THREAD

**Issue by rohit901** [elenapan/dotfiles#127]
Hi, I just installed awesome window manager because I found your desktop really attractive and wanted to install your config files as well for it. But after following almost all the instructions, there seems to be no change when I open my ubuntu session again or restart awesome window manager. 
I get the following error:
```
Oops, there were errors during startup!
error while running function!
stack traceback:
/home/rohit/.config/awesome/rc.lua:189: in main chunk
error: /home/rohit/.config/awesome/rc.lua:189: attempt to call a nil value (field 'connect_signal')

```
I found this issue here: https://github.com/elenapan/dotfiles/issues/44 
And I installed awesome window manager from source again as said there but it didn't fix the problem. 
I also disabled require("evil.mpd") line by commenting out it in init.lua file inside evil folder.
But the problem is still there.
Im running Ubuntu 20.04

When I run 
`systemctl --user start mpd.service`
I get the following output

> Job for mpd.service failed because the control process exited with error code.
> See "systemctl --user status mpd.service" and "journalctl --user -xe" for details.

When I run `systemctl --user status mpd.service`
Output is
```
mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/user/mpd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2020-11-14 12:10:42 IST; 54s ago
TriggeredBy: ● mpd.socket
       Docs: man:mpd(1)
             man:mpd.conf(5)
             file:///usr/share/doc/mpd/html/user.html
    Process: 48780 ExecStart=/usr/bin/mpd --no-daemon (code=exited, status=1/FAILURE)
   Main PID: 48780 (code=exited, status=1/FAILURE)

Nov 14 12:10:42 rohit-Inspiron-5577 systemd[1875]: Starting Music Player Daemon...
Nov 14 12:10:42 rohit-Inspiron-5577 mpd[48780]: exception: Failed to open '/etc/mpd.conf': Permission denied
Nov 14 12:10:42 rohit-Inspiron-5577 systemd[1875]: mpd.service: Main process exited, code=exited, status=1/FAILURE
Nov 14 12:10:42 rohit-Inspiron-5577 systemd[1875]: mpd.service: Failed with result 'exit-code'.
Nov 14 12:10:42 rohit-Inspiron-5577 systemd[1875]: Failed to start Music Player Daemon.

```

I really like your desktop and would love to have the same as well, I have instaleld all the fonts/dependencies etc but its still not working. Could you please let me know how to fix this?

**Comment by rohit901** [comment]
Sorry, I forgot to install the deb package after building it from source

**Comment by thien0709** [comment]
I suffer from the same problem as you. I use Arch Awesome WM, how can I edit them?
