### ISSUE TITLE
Beginner-friendly instructions?

### ISSUE THREAD

**Issue by robhutters** [elenapan/dotfiles#13]
Hi!

**In brief:** I don't understand where to put all these files. I feel like I'm in way over my head. Would you mind adding clearer instructions for people who are new to window managers? 

I'm an inexperienced WM-user. Not an inexperienced UNIX/UNIX-like user.

I did as you said and played around with the default theme at first. It went smoothly. Installed Termite, Rofi, Firefox, and Nemo. No issues, save for a path issue while installing Termite. No problem.

Cloned your repo to my Pi (Debian-based). 

This is where I got lost. 

Do I copy the contents of your `config` folder to `.config` ? I did this, but x-server won't start.
What do I do with the rest of the folders? Do I need to copy them to ~/ ?

**Comment by elenapan** [comment]
The `config` folder in my repo corresponds to `~/.config` in your system.
The only folder you really need from my repo in order to try this setup is `config/awesome`. 
Optionally, you can put the scripts included in the `bin` folder somewhere in your `$PATH`.
Also, since you have Rofi and Termite already installed you do not even need to edit `~/.config/awesome/rc.lua` to set default applications.

So in short:
```bash
git clone https://github.com/elenapan/dotfiles.git elenapan-dotfiles # Clone repo
mv ~/.config/awesome ~/.config/awesome-old # Backup old configuration
cp -r elenapan-dotfiles/config/awesome ~/.config # Copy repo's awesome configuration folder to ~/.config
```
And you should be good to go.

Now, about X not starting, you mentioned using a Debian based system. I am guessing AwesomeWM's version in your distro's official repos might be a little bit old. Running `awesome -v` should give you version 4.2+ else it will not work. In that case I suggest compiling Awesome from source so you get the most recent version and then try again.

**Comment by robhutters** [comment]
Thanks for the clear instructions. That's surprisingly easy. 

Turns out I was running a much older version of Awesome! 

It has since been deleted.

I've been trying to compile Awesome from scratch for the past four hours, but no luck.
```
[ 26%] Checking for LGI...
Building for Lua 5.3.
Error: [string "print(string.format('Building for %s.', jit a..."]:2: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file '/usr/local/share/lua/5.3/lgi/version.lua'
	no file '/usr/local/share/lua/5.3/lgi/version/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi/version.lua'
	no file '/usr/local/lib/lua/5.3/lgi/version/init.lua'
	no file '/usr/share/lua/5.3/lgi/version.lua'
	no file '/usr/share/lua/5.3/lgi/version/init.lua'
	no file './lgi/version.lua'
	no file './lgi/version/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi/version.so'
	no file '/usr/lib/arm-linux-gnueabihf/lua/5.3/lgi/version.so'
	no file '/usr/lib/lua/5.3/lgi/version.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lgi/version.so'
	no file '/usr/local/lib/lua/5.3/lgi.so'
	no file '/usr/lib/arm-linux-gnueabihf/lua/5.3/lgi.so'
	no file '/usr/lib/lua/5.3/lgi.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lgi.so'


       WARNING
       =======

 The lgi check failed.
```

It tries to build for lua5.3. No problem. `[sudo find / -name 'lua5.3']`

```
/usr/include/lua5.3
/usr/bin/lua5.3
/usr/share/doc/lua5.3
/usr/share/lua5.3
```

Compiled lgi from scratch but it only created links to `[sudo find / -name 'lgi']` 

```
/usr/lib/arm-linux-gnueabihf/lua/5.2/lgi
/usr/lib/arm-linux-gnueabihf/lua/5.1/lgi
/usr/local/lib/luarocks/rocks/lgi
/usr/local/lib/lua/5.1/lgi
/usr/local/share/lua/5.1/lgi
/usr/share/lua/5.2/lgi
/usr/share/lua/5.1/lgi
```
... and not lua5.3.

As you can see, I also tried to install it with `luarocks`, but the compiler doesn't look there. I have been wanting to write it in, but don't know where. Been looking.

I would install the lua5.3-lgi package if I could, but it doesn't exist for `Raspbian` as far as I can tell. 

Debian Buster [I run `Raspbian Stretch`] does have Awesome4.3 and lua5.3-lgi. But I'm weary of installing packages not meant for my distro. I have bricked many a Pi this way. 

There should be a way to compile a lua5.3-lgi package myself, but I haven't the foggiest how to go about doing that. I could always learn, but that sounds like a huge time sink. 

Perhaps I could symlink the versions I have to where the compiler expects them to be.

What do you think? 

Otherwise I'll go bother the guys at Awesome. This isn't an issue related to your theme.

**Comment by elenapan** [comment]
Glad it worked!
> The correct path was different though.

Woops, thank you for letting me know, I fixed it.
