### ISSUE TITLE
Just a question:

### ISSUE THREAD

**Issue by HolySuicidalTurkey** [elenapan/dotfiles#138]
In the default config file, rc.lua, there is a section that goes like this:

```user = {
    -- >> Default applications <<
    -- Check apps.lua for more
    terminal = "kitty -1",
    floating_terminal = "kitty -1",
    browser = "firefox",
    file_manager = "kitty -1 --class files -e ranger",
    editor = "kitty -1 --class editor -e vim",
    email_client = "kitty -1 --class email -e neomutt",
    music_client = "kitty -o font_size=12 --class music -e ncmpcpp",
```

this is more of a question i had than anything else:
1.) What is kitty? It's just a terminal, right?
2.) why are you using things like `editor = "kitty -1 --class editor -e vim",`  instead of just `editor="vim"`
3.) Is there a reason your formatted it that way? Because it's not working when i tried to switch my apps.
4.) How important is it that it's set up like that, because none of my buttons are working.
5.) I don't have kitty installed. I have terminator with fish shell. How do I properly set up my apps?

**Comment by PedramNavid** [comment]
not elena but ..

1) Kitty is a terminal, like urxvt or alacritty
2) You can set the class name of the terminal to reference using rules https://github.com/elenapan/dotfiles/blob/e952184146525f8d75ccfccb187938de1efafc54/config/awesome/rc.lua#L908
3) Do you have kitty installed?
4) if your bbuttons arent working it could be a bigger issue with your config. Do you have the git version of awesome installed?
5) install kitty or update references to kitty to the termianl of your choice.

**Comment by HolySuicidalTurkey** [comment]
no, I don't have Kitty. I use Terminator.

Do i still need the -1 and -e in these lines? What do they do? Do they work with Terminator? I deleted them from my version.
https://github.com/elenapan/dotfiles/blob/e952184146525f8d75ccfccb187938de1efafc54/config/awesome/rc.lua#L83

I have Git version of Awesome.

Is it really just as simple as replacing the word "kitty" with "terminator"?

**Comment by HolySuicidalTurkey** [comment]
Okay I fixed the buttons.

however, I still don’t like the buttons in the app drawer. How do I change that?

**Comment by HolySuicidalTurkey** [comment]
imma just close this, is figured out.

Now i just have a bug with the fonts
