### ISSUE TITLE
Applets? Network manager applet?

### ISSUE THREAD

**Issue by mkevac** [elenapan/dotfiles#139]
Hi.

How do I work with apps that have applets? Icons that usually reside in the upper-right corner in Gnome/MacOS.
For example, I am using Network Manager, and its applet to connect to VPN. Also, I am using flameshot screenshot app that has this applet.

Thank you.

**Comment by dorgnarg** [comment]
Meta+= is the default mapping for the dock, in Amarena it'll bring up a little box in the bottom-right and that's where application's applets live. You may have to manually startup nm-applet though, or set it to auto-start

**Comment by mkevac** [comment]
Thank you very much.
On my wide screen (5120x1440) many things are not where they are supposed to be (this dock is almost in the middle of the screen), but that is a different problem.
