### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by murilo-menezes** [elenapan/dotfiles#141]
I installed awesomeWM today, I installed your dotfiles, but I personally doesnt liked it, is there a way to complete remove this?

P.S.: My KDE Plasma is not working anymore

**Comment by ceuk** [comment]
Just delete all the files? It's not like there's an installation script 
so you will have copied everything manually. Just go through the same 
process backwards

**Comment by murilo-menezes** [comment]
thanks
