### ISSUE TITLE
brightness keys

### ISSUE THREAD

**Issue by sharktie005** [elenapan/dotfiles#143]
hi. i looked around in the keybinds file but couldn't quite figure out how to change it so the keys at F1 and F2 change brightness. I'm new to this whole thing and wanted to start from someone else's config files. If you could please let me know where to change them that would be great. Thank you

**Comment by sharktie005** [comment]
i did try that but found no change. I'm on a laptop so maybe the need to press the function key is messing with it. i did try pressing function + F1 but that didn't work either. The audio controls work though so i tried using those but i don't understand how they work seeing as they are assigned to F1 F2 and F3 even though i have it on F10 F11 and F12 on mine. It might be an issue on my side in which case ill be able to ask somewhere else. Thanks!

**Comment by phob0s-pl** [comment]
I have fixed similar issue. First of all to see light errors type:
`light -U 10 -v 3`

I needed to add my user to video group:
`sudo usermod -a -G video phob0s`

And store minimal value:
`light -N 0`

Its worth to store current value of light:
`light -O`

**Comment by sharktie005** [comment]
Yes! Thanks a lot for this. I had to edit permissions for  sys/class/backlight/intel_backlight/brightness and allow it to be edited. Along with setting the minimal and current value.
