### ISSUE TITLE
Skyfall theme font

### ISSUE THREAD

**Issue by Zander-Labuschagne** [elenapan/dotfiles#15]
Hello,

Great work on the new skyfall theme :). I am having a problem with the weather icon font in the bottom bar. When I open the text_weather.lua file it shows the icons as empty blocks. I have the nerd-fonts-complete package installed from the AUR and had no problems with the lovelace theme. Which fonts are you using? Thank you!

**Comment by elenapan** [comment]
Ah, you need to install Typicons as well. They are used for the taglist, weather as well as logout screen.

**Comment by Zander-Labuschagne** [comment]
Wow that is much better. Thank you, have a great weekend!
