### ISSUE TITLE
Error after restarting

### ISSUE THREAD

**Issue by Glonk-0** [elenapan/dotfiles#153]
![IMG_20210812_215303.jpg](https://user-images.githubusercontent.com/52832125/129235354-836e9cec-8a77-41f4-a2b7-7514842a9fbc.jpg)

**Comment by mattcoding4days** [comment]
It is likely that you are not running the development version of awesome.
This thread here explains it [connect_signal issue](https://www.reddit.com/r/awesomewm/comments/i4axjq/naughtyconnect_signal_doesnt_exist/)

This is why in the install instructions for this config it states that you must install the `awesome-git` release. Now if you aren't on Arch, just go to the awesome github repo, follow the instructions and build from source. Its a few simple make commands, you will need cmake installed etc.

**Comment by elenapan** [comment]
Yep, matt is correct. This should be resolved by installing `awesome-git`.
