### ISSUE TITLE
Uptime not showing anymore, is it just here?

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#155]
![uptime](https://user-images.githubusercontent.com/17055027/130372757-05fa5d81-5b9e-4429-819a-19abe095ad5b.png)

Found this today when looking at the dashboard.

**Comment by Jasper1378** [comment]
This probably isn't the _proper_ way to do it. But my workaround is to remove the second part of the uptime command (that contains sed) so that the second line in the uptime section in /elemental/dashboard/amarena.lua says `awful.widget.watch("uptime -p", 60, function(_, stdout)`
