### ISSUE TITLE
When I launch awesome it shows error

### ISSUE THREAD

**Issue by anonygituser** [elenapan/dotfiles#158]
`error while running function!
stack traceback:
    /home/user/.config/awesome/rc.lua:189 in main chunk
error: /home/user/.config/awesome/rc.lua:189 attempt to call a nil value (field 'connect_signal')`

**Comment by DerpTaterTot** [comment]
Did you install the git version of awesome?

**Comment by elenapan** [comment]
Yep, this error should disappear if you install the git version of awesome.
Duplicate of https://github.com/elenapan/dotfiles/issues/42 (among others).
