### ISSUE TITLE
Help with antialising on all clients

### ISSUE THREAD

**Issue by AdsonCicilioti** [elenapan/dotfiles#163]
Hi @elenapan ! Greetings!

Nice and beautiful work u made here!

About the antialising trick, does how i can apply on all default clients?

My round corners more seems with an shark teeths.. lol

![image](https://user-images.githubusercontent.com/6278398/140538346-145a5bcd-0045-4f1c-8cf1-e794262b08c0.png)

I'm still learning Lua and Awesome classes, and I still haven't been able to use their nice anti-aliasing strategy to apply to all clients.

Would you help me?

**Comment by cortex3** [comment]
I'm personally using this picom fork for my rounded corners https://github.com/ibhagwan/picom
I'm assuming @elenapan might use picom too since the following was commented by default:
```-- This decoration theme will round clients according to your theme's
-- border_radius value
-- Disable this if using `picom` to round your corners
-- decorations.enable_rounding()
```

**Comment by elenapan** [comment]
Indeed I use `picom` for this. Please check out [this wiki article](https://github.com/elenapan/dotfiles/wiki/Rounded-corners#rounded-corners).
