### ISSUE TITLE
Perma Floating 

### ISSUE THREAD

**Issue by Decapitater** [elenapan/dotfiles#166]
<h4> hi i wanted to know how to set windows in permanent floating , every time i log in i would need to manually win+shift+s to get the floating format is there a way to keep it on default and use win+shift+s to shift to tiling or fullscreen format when needed </h4>

<h2>tldr: want to set floating format as default without using shortcut key win+shift+s every time</h2>

**Comment by Decapitater** [comment]
@ceuk @elenapan  ?

**Comment by elenapan** [comment]
Hi there,

You can set all layouts to `l.floating` here:

https://github.com/elenapan/dotfiles/blob/e952184146525f8d75ccfccb187938de1efafc54/config/awesome/rc.lua#L307-L319

**Comment by Decapitater** [comment]
@elenapan i thank you for responding and solving my problem if the time would allow me i would create a live iso with the same environment as the one i am currently using (a modified version of yours) or a iso for arm based rpi
