### ISSUE TITLE
Many widgets do not work properly (or at all) with multiple monitors

### ISSUE THREAD

**Issue by elenapan** [elenapan/dotfiles#17]
Edit:

**List of fixed widgets**
-
- [x] Lovelace taglist
- [x] Skyfall taglist
- [x] Sidebar

   Not sure how to handle this yet. Suggestions? How would you like the sidebar to work on your setup?
- [x] App drawer

   Should appear on your focused screen and maybe dim other screens.
- [x] Lock screen
   Thanks to @hellkitten9 
- [x] Start screen
    Should appear on your focused screen and maybe dim other screens.

**Comment by dadmcleader** [comment]
Any way to make them work for dual monitor setup? 
thanks!

**Comment by elenapan** [comment]
Unfortunately, not until I fix it. If you would like to use this config with multiple monitors for the time being, I suggest replacing these widgets with AwesomeWM's "native" taglist.

**Comment by dadmcleader** [comment]
ok nvm thanks.I already did that .Great job with your config btw.its really beautiful!

**Comment by elenapan** [comment]
As of the latest commit, Lovelace and Skyfall taglists now work with multiple monitors.

**Comment by NeoScaler** [comment]
Would like to add that the new lock screen only locks one screen, which is if you use multiple screens ... not very secure.

**Comment by NeoScaler** [comment]
For me, the taglist and wibar is duplicated on my main screen when I am using a dual screen setup. Please see the screenshot here: https://imgur.com/a/DQ5JtQf

**Comment by elenapan** [comment]
> the taglist and wibar is duplicated

Hmm that is strange. Could you please also try the `lovelace`or `skyfall`  bar themes (you can change the bar theme easily at the top of my `rc.lua`), as well as try the default `rc.lua` with a dual monitor setup? If you built from source, you can grab the default `rc.lua` from `awesomerc.lua` in the git repo.

**Comment by NeoScaler** [comment]
> > the taglist and wibar is duplicated
> 
> Hmm that is strange. Could you please also try the `lovelace`or `skyfall` bar themes (you can change the bar theme easily at the top of my `rc.lua`), as well as try the default `rc.lua` with a dual monitor setup? If you built from source, you can grab the default `rc.lua` from `awesomerc.lua` in the git repo.

Can't start skyfall because of a nil global icon path, but lovelace is working fine. Wibar is on each monitor.

**Comment by elenapan** [comment]
Thanks for testing that. It was an easy fix. I pushed it to the repo, but if you want to quickly fix it yourself, just go to `bars/ephemeral.lua` and set `screen = s` somewhere in the wibar declaration for both `s.mywibox` and `s.mytopwibox`.

Here is the diff:
```diff
--- a/config/awesome/bars/ephemeral.lua
+++ b/config/awesome/bars/ephemeral.lua
@@ -266,7 +266,7 @@ awful.screen.connect_for_each_screen(function(s)


     -- Create the wibox
-    s.mywibox = awful.wibar({visible = true, ontop = true, type = "dock", position = "bottom"})
+    s.mywibox = awful.wibar({screen = s, visible = true, ontop = true, type = "dock", position = "bottom"})
     s.mywibox.height = beautiful.wibar_height
     -- s.mywibox.width = beautiful.wibar_width

@@ -293,7 +293,7 @@ awful.screen.connect_for_each_screen(function(s)


     -- Create the top bar
-    s.mytopwibox = awful.wibar({visible = true, ontop = false, type = "dock", position = "top", height = dpi(5)})
+    s.mytopwibox = awful.wibar({screen = s, visible = true, ontop = false, type = "dock", position = "top", height = dpi(5)})
     -- Bar placement
     awful.placement.maximize_horizontally(s.mytopwibox)
     s.mytopwibox.bg = "#00000000"

```


I also fixed a typo in skyfall that was causing an error.

**Comment by NeoScaler** [comment]
Thanks, was just about to prepare this as PR, as I fixed it as well, but you were faster.

**Comment by elenapan** [comment]
The issues should be fixed now.
