### ISSUE TITLE
How to change dock

### ISSUE THREAD

**Issue by monkeboi9** [elenapan/dotfiles#172]
Im trying to figure out how to change the applications on the dock.

**Comment by jasper1378** [comment]
If you're referring to the bottom bar, they're not actually applications, but rather icons to help you differentiate between your various workspace. I'm assuming you have `bar_themes` in `rc.lua` set to `lovelace`.

That being said, you can change the icons by editing `awesome/themes/lovelace/theme.lua` (around line 192). The icon set that is used in the `lovelace` bottom bar is contained in `awesome/icons/linebit`.

I hope that helps!

**Comment by monkeboi9** [comment]
I was reffering to the dock that pops up when you press ctrl + b in Amarena

**Comment by jasper1378** [comment]
My apologies. In that case you'll want to edit `awesome/noodle/dock.lua` around line 45. Furthermore the default apps referred to in `dock.lua` can be changed in `awesome/apps.lua` and `awesome/rc.lua` around line 77.

**Comment by monkeboi9** [comment]
Thank You!
