### ISSUE TITLE
More a hint then a issue ;)

### ISSUE THREAD

**Issue by lutzmor** [elenapan/dotfiles#18]
Hey,

first of all beautiful work you did there! Maybe you want to add "even-better-ls" to the deps, i searched for nearly a day until i found out that you used this package ( tried ls-icons before ).

Greetings :)

**Comment by elenapan** [comment]
Thank you for your feedback.
I commented out the `even-better-ls` section in `.zshrc` so that zsh does not whine about it, and added `even-better-ls` in the "Eye-candy suggestions" section as it is completely optional.
