### ISSUE TITLE
Dropbox links are down

### ISSUE THREAD

**Issue by Armadillidiid** [elenapan/dotfiles#181]
Can't download custom font and icons as the Dropbox links are no longer functional

**Comment by Clutchnp** [comment]
I am not sure and this is very late but i think the icon packs and fonts are included in this repository in the misc/fonts folder:)

**Comment by itstoxicqt** [comment]
> I am not sure and this is very late but i think the icon packs and fonts are included in this repository in the misc/fonts folder:)

I mean this repo hasn't been updated in years idk why people still post issues the project has obviously been abandoned

**Comment by elenapan** [comment]
The dropbox link has been updated. Now it points to a .zip with all required fonts.
