### ISSUE TITLE
Error when trying to do "systemctl --user start mpd.service"

### ISSUE THREAD

**Issue by PWDSerialgamer07** [elenapan/dotfiles#182]
When I try to do that command, I get the error:
Loaded: loaded (/usr/lib/systemd/user/mpd.service; enabled; preset: enabled)
Active: failed (Result: exit-code) since Wed 2023-04-12 19:04:37 +00; Imin 9s ago Docs: man:mpd(l)
man:mpd.conf(5)
Process: 16725 ExecStart=/usr/bin/mpd —systemd (code=exited, status=l/FAILURE) Main PID: 16725 (code=exited, status=l/FAILURE)
CPU: 68ms
Apr 12 19:04:37 fartox systemd[349]: Starting Music Player Daemon...
Apr 12 19:04:37 fartox mpd[16725]: Ignoring the 'pid_file' setting in systemd mode Apr 12 19:04:37 fartox mpd[16725]: server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600’ succeeded): Failed to bi>
Apr 12 19:04:37 fartox mpd[16725]: decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Apr 12 19:04:37 fartox mpd[16725]: exception: Failed to open '/var/lib/mpd/mpd.db': No such file or directory
Apr 12 19:04:37 fartox mpd[16725]: exception: Failed to open database plugin; Can't create db file in "/var/lib/mpd": Permission denied
Apr 12 19:04:37 fartox systemd[349]: mpd.service: Main process exited, code=exited, status=l/FAILURE
Apr 12 19:04:37 fartox systemd[349]: mpd.service: Failed with result 'exit-code'.
Apr 12 19:04:37 fartox systemd[349]: Failed to start Music Player Daemon.

**Comment by elenapan** [comment]
MPD needs to be configured first to set `db_file` (at least).

See https://wiki.archlinux.org/title/Music_Player_Daemon#Configure_the_location_of_files_and_directories
