### ISSUE TITLE
change urxvt class flag to "-T"

### ISSUE THREAD

**Issue by BassMatt** [elenapan/dotfiles#24]
in the readme, you say...

`urxvt -t "Music Terminal" -e ncmpcpp`

however, -t is an unrecognized flag for urxvt, I think instead it should be 

`urxvt -T "Music Terminal" -e ncmpcpp`

... btw thanks for these _awesome_ dotfiles, I've been poking and prodding trying to get all the functionality working.

**Comment by elenapan** [comment]
Thanks for reporting this!
Fixed with 35e050e82f41a37a321bfbb4863d6e004f166ef5
