### ISSUE TITLE
awesomewm scratchpad

### ISSUE THREAD

**Issue by BassMatt** [elenapan/dotfiles#26]
I'm looking at how you're using scratchpad in your config files...

From what I understand, is it effectively a way to "minimize" a window?

I'm having trouble getting it to work (middle click on start icon). Is there a dependency required?

**Comment by elenapan** [comment]
The "dependency" for the scratchpad keybind to work is just to have a window with class name "scratchpad" open.

When you use the keybind:
- If the scratchpad window is focused: It is moved to tag 10 which is my miscellaneous tag. (For some reason, minimizing it did not work, that is why I am using this method until I figure out what is wrong.)
- If it is not focused: It is moved to your current tag, raised, and focused.

I use it as neat way to bring up a specific terminal into focus wherever it is, without having to move to another tag, and also quickly hide it with the same keybind.

Check out this better implementation which allows you to set any window class or name as a scratchpad.
https://github.com/notnew/awesome-scratch

**Comment by elenapan** [comment]
I have included the `scratchpad` script I use to launch my scratchpad. It should work out of the box now with this config.
