### ISSUE TITLE
text_taglist error

### ISSUE THREAD

**Issue by victorhgo** [elenapan/dotfiles#33]
Well, I just switched from i3wm after I saw your post on r/unixporn. I'm trying to use your configuration, and this error message keeps showing on my screen:
`Oops, an error happened!
.config/awesome/noodle/text_taglist.lua88: attempt to index a nil value (field 'taglist_text_occupied')
Oops, an error happened!
.config/awesome/noodle/text_taglist.lua84: attempt to index a nil value (field 'taglist_text_focused')`

I know it might be a simple error, or something I've done wrong. But as I said, I'm completely new at Awesome, and I'm enjoying it so much thank to your configuration

![2019 05 01-19 10 49 screenshot](https://user-images.githubusercontent.com/39852859/57046233-32f5f080-6c46-11e9-9b6d-dd4ee3c98d18.png)

**Comment by elenapan** [comment]
Hello there,

This is actually a bug with the error notifications that happens because I have moved the error handling  too low, while it should be done as early as possible in the config (I will fix this soon).

The real error that causes this is overwritten by these notifications.

It is usually a syntax error (like a forgotten `,` or `=`). In order to debug this you could install Xephyr (in most distros the package is called `xorg-xephyr` or `xserver-xephyr`)
and run in a terminal:
```shell
Xephyr :1 -screen 1366x768 &
DISPLAY=:1 awesome
```

This will start awesome in a separate window. I would like you to paste the output from that terminal here when the error happens. All the errors should be there, and the most relevant ones should be first.

**Comment by elenapan** [comment]
Fixed the taglist errors appearing with 3e130fc6cf63f3dfc8563006a5a23aa431a8a611.
Can you try again with the updated `text_taglist.lua`?

**Comment by victorhgo** [comment]
Hi, how are you? I'm sorry for my late reply. I was quite busy the past few days. 

Well, I did what you told me to do. And this is the entire output from terminal:
`Xephyr :1 -screen 1366x768 & DISPLAY=:1 awesome
[1] 4083
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
Errors from xkbcomp are not fatal to the X server
kill: not enough arguments
kill: not enough arguments
mpd error: Connection refused
zsh:1: no such file or directory: /home/victor/.fehbg
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:90: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:308: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:90: attempt to index a nil value (field 'taglist_text_empty')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:108: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:291: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:308: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:313: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:317: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:321: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:326: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:331: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:335: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:339: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:343: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
2019-05-04 23:23:21 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/victor/.config/awesome/noodle/text_taglist.lua:84: in upvalue 'update_widget'
	/home/victor/.config/awesome/noodle/text_taglist.lua:114: in upvalue 'func'
	/usr/share/awesome/lib/awful/tag.lua:1525: in function </usr/share/awesome/lib/awful/tag.lua:1523>
	[C]: in metamethod '__newindex'
	/usr/share/awesome/lib/awful/tag.lua:283: in function 'awful.tag.add'
	/home/victor/.config/awesome/rc.lua:347: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/victor/.config/awesome/rc.lua:292: in main chunk
error: /home/victor/.config/awesome/noodle/text_taglist.lua:84: attempt to index a nil value (field 'taglist_text_focused')
/home/victor/.config/awesome/autostart.sh: line 12: numlockx: command not found
2019-05-04 23:23:22 W: awesome: a_glib_poll:438: Last main loop iteration took 0.239527 seconds! Increasing limit for this warning to that value.
2019-05-04 23:23:22 E: awesome: Error during a protected call: /home/victor/.config/awesome/noodle/mpd_song.lua:90: bad argument #1 to 'gsub' (string expected, got nil)
stack traceback:
	[C]: in function 'string.gsub'
	/home/victor/.config/awesome/noodle/mpd_song.lua:90: in function </home/victor/.config/awesome/noodle/mpd_song.lua:82>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:481: in function </usr/share/awesome/lib/awful/spawn.lua:475>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:577: in upvalue 'done'
	/usr/share/awesome/lib/awful/spawn.lua:592: in function </usr/share/awesome/lib/awful/spawn.lua:584>
exception: Failed to open '/home/victor/.config/mpd/mpd.conf': No such file or directory
2019-05-04 23:24:06 E: awesome: a_xcb_io_cb:402: X server connection broke (error 1)
Gdk-Message: 23:24:06.614: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

[1]  + 4083 exit 1     Xephyr :1 -screen 1366x768
`

**Comment by elenapan** [comment]
Hello there,

First of all I suggest you grab the updated [text_taglist.lua](https://github.com/elenapan/dotfiles/blob/master/config/awesome/noodle/text_taglist.lua) in order to get rid of those useless taglist errors.

The relevant errors from your logs are the following:
`2019-05-04 23:23:22 E: awesome: Error during a protected call: /home/victor/.config/awesome/noodle/mpd_song.lua:90: bad argument #1 to 'gsub' (string expected, got nil)`
and
`exception: Failed to open '/home/victor/.config/mpd/mpd.conf': No such file or directory`

I am guessing you do not have an `mpd` configuration file, or if you do, it is named differently than `mpd.conf`. Thus, `mpd` fails to start, `mpc` fails to get the song info, and the music widget throws an error due to empty output.

 In `config/awesome/autostart.sh`, I point `mpd` to a specific configuration file. You should change that to point to your configuration file. After you restart Awesome, make sure that:

- `mpd` is running (`pgrep mpd` should print a number)
- `mpc` does not return any errors like "Connection refused" when you run it in terminal

Let me know how it goes.

**Comment by victorhgo** [comment]
I did what you told me to do. And now it works perfectly!!! 

I really appreciate your help, because I love your configurations, it is just amazing what you've done with Awesome. Thank you very much for your time and attention.

I only need to get used with Awesome commands, it's a little bit different from my old i3wm setup, but I'll get used to it soon.

Have a nice week :D

**Comment by elenapan** [comment]
I am glad it works.

Thank you for your kind words, I am very happy to hear that you are enjoying this configuration!
