### ISSUE TITLE
GTK Theme

### ISSUE THREAD

**Issue by ptrxyz** [elenapan/dotfiles#34]
Nice work, but do you also use a matching GTK2/3 theme? If so, what would you recommend?

Cheers and keep it up!

**Comment by elenapan** [comment]
Yes I use one, you can find all the GTK themes I uploaded in the `misc/gtk`directory of this repo.

All of them are generated with [oomox](https://github.com/themix-project/oomox/) so the colors match perfectly with the rest of the desktop.

**Comment by Hkyx** [comment]
Hi @elenapan where is the config to select the gtk theme ? grep don't return anything on that
