### ISSUE TITLE
Calendar setup

### ISSUE THREAD

**Issue by MPE2016** [elenapan/dotfiles#35]
How have you set up the calendar widget?

**Comment by elenapan** [comment]
https://github.com/elenapan/dotfiles/blob/544fb16561bc50508cfe0988c937bb92678959d1/config/awesome/noodle/start_screen.lua#L117-L204

**Comment by MPE2016** [comment]
thanks!
2019-05-21 04:13 GMT+02:00 elenapan<notifications@github.com>:
