### ISSUE TITLE
Broken checkbox and radio button in GTK themes (lovelace)

### ISSUE THREAD

**Issue by unorderedlist** [elenapan/dotfiles#36]
I am getting large red boxes with no tick mark in them, which makes it hard for navigation and other stuff. As shown below. I spent some time checking the whole GTK theme files but found nothing. Please help. 
![Screenshot_2019-05-26_19-47-59](https://user-images.githubusercontent.com/19857414/58383020-32efd300-7fef-11e9-86a5-eefb6db90139.png)

**Comment by elenapan** [comment]
This is strange, I have never seen it before.
Do the other themes work for you (manta and skyfall)?
Also can you try using a different icon theme?

If it persists I guess I could generate it again with a newer version of Oomox.

**Comment by unorderedlist** [comment]
[Thanks for replying!]
Yeah! This seems so odd.
And, no the other themes (manta and skyfall) also have the similar issues.
I tried with other icon theme.
Though, I found one thing, i.e. the animation of checking and unchecking works perfectly, which suggests there might some small issue regarding this weird behavior of the check boxes and radio buttons.

And, since the animation functions properly, there's not much of issue technically which restricts the daily usage, but yeah this seems very odd.

**Comment by unorderedlist** [comment]
[Thanks for replying!]
Yeah! This seems so odd.
And, no the other themes (manta and skyfall) also have the similar issues.
I tried with other icon theme.
Though, I found one thing, i.e. the animation of checking and unchecking works perfectly, which suggests there might some small issue regarding this weird behavior of the check boxes and radio buttons.
And, since the animation functions properly, there's not much of issue technically which restricts the daily usage, but yeah this seems very odd.


PS. : It's a great theme. Works perfectly for AwesomeWM. And, I will also try to figure out using Oomox.

**Comment by elenapan** [comment]
I am guessing it has to do with your version of GTK. Maybe it is too new or too old?
In any case, I would also try other GTK themes that are not generated by Oomox, for example [Arc](https://github.com/horst3180/arc-theme/) or [Sweet](https://github.com/EliverLara/Sweet).

**Comment by unorderedlist** [comment]
I tried with a simple theme, that i made with Oomox. Nothing highly customized but, that didn't had the the issue like this one. I don't know what might be the problem. I entirely went through the gtk2.0/ and gtk3.0l files and saw the whole CSS and the SVGs. But, i did find any issue. And, I using it on Manjaro. Perhaps, the version of GTK might not be a problem. Anyways, it might be something else.

**Comment by elenapan** [comment]
I see.
Well since it works with your Oomox, here is a template for a Lovelace colored GTK theme.
Save it in `~/.config/oomox/colors/lovelace` and when you open Oomox it should appear in User presets. Hopefully when you generate it, it will work as expected.

```
ACCENT_BG=5ADECD
ARC_TRANSPARENCY=True
ARC_WIDGET_BORDER_COLOR=414458
BASE16_GENERATE_DARK=False
BASE16_INVERT_TERMINAL=False
BASE16_MILD_TERMINAL=False
BG=1D1F28
BTN_BG=1D1F28
BTN_FG=FDFDFD
BTN_OUTLINE_OFFSET=-3
BTN_OUTLINE_WIDTH=1
CARET1_FG=FDFDFD
CARET2_FG=FDFDFD
CARET_SIZE=0.04
CINNAMON_OPACITY=1.0
FG=FDFDFD
GRADIENT=0.0
GTK3_GENERATE_DARK=False
HDR_BG=1D1F28
HDR_BTN_BG=1D1F28
HDR_BTN_FG=FDFDFD
HDR_FG=FDFDFD
ICONS_ARCHDROID=C574DD
ICONS_DARK=282A36
ICONS_LIGHT=8897F4
ICONS_LIGHT_FOLDER=FDFDFD
ICONS_MEDIUM=C574DD
ICONS_NUMIX_STYLE=0
ICONS_STYLE=papirus_icons
ICONS_SYMBOLIC_ACTION=FDFDFD
ICONS_SYMBOLIC_PANEL=FDFDFD
MATERIA_PANEL_OPACITY=1.0
MATERIA_SELECTION_OPACITY=1.0
MATERIA_STYLE_COMPACT=True
MATERIA_SURFACE=282A36
MATERIA_VIEW=1D1F28
MENU_BG=282A36
MENU_FG=FDFDFD
NAME=lovelace
OUTLINE_WIDTH=1
ROUNDNESS=6
SEL_BG=C574DD
SEL_FG=1D1F28
SPACING=3
SPOTIFY_PROTO_BG=1D1F28
SPOTIFY_PROTO_FG=FDFDFD
SPOTIFY_PROTO_SEL=B043D1
TERMINAL_ACCENT_COLOR=C574DD
TERMINAL_BACKGROUND=1D1F28
TERMINAL_BASE_TEMPLATE=tempus_future
TERMINAL_COLOR0=F37F97
TERMINAL_COLOR1=F37F97
TERMINAL_COLOR10=18E3C8
TERMINAL_COLOR11=FF8037
TERMINAL_COLOR12=556FFF
TERMINAL_COLOR13=B043D1
TERMINAL_COLOR14=3FDCEE
TERMINAL_COLOR15=BEBEC1
TERMINAL_COLOR2=5ADECD
TERMINAL_COLOR3=F2A272
TERMINAL_COLOR4=8897F4
TERMINAL_COLOR5=C574DD
TERMINAL_COLOR6=79E6F3
TERMINAL_COLOR7=FDFDFD
TERMINAL_COLOR8=414458
TERMINAL_COLOR9=FF4971
TERMINAL_FOREGROUND=FDFDFD
TERMINAL_THEME_ACCURACY=122
TERMINAL_THEME_AUTO_BGFG=True
TERMINAL_THEME_EXTEND_PALETTE=True
TERMINAL_THEME_MODE=auto
THEME_STYLE=materia
TXT_BG=282A36
TXT_FG=BEBEC1
UNITY_DEFAULT_LAUNCHER_STYLE=False
WM_BORDER_FOCUS=1D1F28
WM_BORDER_UNFOCUS=1D1F28
```

**Comment by unorderedlist** [comment]
Thanks, I will try it out.
