### ISSUE TITLE
How to make wifi widget appear?

### ISSUE THREAD

**Issue by tiwalayo** [elenapan/dotfiles#37]
One of the issues I had been having with the Lovelace was that I couldn't find a way to connect to/from wifi without logging into the vanilla Ubuntu environment.

To my surprise, I recently found a small grey widget in the bottom left gap of my screen that seemed to control wifi. Unfortunately, on the next boot, it was gone. Would you happen to know what shortcut I need to toggle that widget on/off?

**Comment by elenapan** [comment]
That widget is called the `tray` and there is a keybind to toggle it: `super + =`

Also in the Lovelace theme you can toggle it by middle clicking on the leftmost button on the bar.

**Comment by tiwalayo** [comment]
Thanks!
