### ISSUE TITLE
title bar has no min/max/close buttons

### ISSUE THREAD

**Issue by arsdragonfly** [elenapan/dotfiles#39]
[Imgur](https://i.imgur.com/xFZiloC.png)

**Comment by elenapan** [comment]
I had them disabled on my new theme. In order to re-enable them, go to titlebars.lua and search for the comment that says "Titlebar items".
Then you can enable whichever buttons you want by uncommenting them:
```lua
awful.titlebar.widget.minimizebutton(c),
awful.titlebar.widget.maximizedbutton(c),
awful.titlebar.widget.closebutton(c),
```

**Comment by arsdragonfly** [comment]
Good to know. Thanks!
