### ISSUE TITLE
Just to let you know...

### ISSUE THREAD

**Issue by maxdevjs** [elenapan/dotfiles#4]
Awesome 4.2-525... + your config running in [Xephyr](https://en.wikipedia.org/wiki/Xephyr) under i3 etc etc.

![a](https://user-images.githubusercontent.com/22229196/50430787-3e5a9900-08ad-11e9-80b6-9d0a8243ef6e.png)

**Comment by elenapan** [comment]
Nice! Any issues with it?

**Comment by maxdevjs** [comment]
No issues. As it has been a test, I did not configure everything (weather, specific scripts). Just dropped your Awesome's config and most of it worked out of the box: I could play music, but not set volume... Very pleasant to use, smooth and gorgeous :)

Only note is that I had to use Ubuntu, Awesome is not that easy to install on Solus (and, in fact, I did not install it there).

**Comment by elenapan** [comment]
Glad that it works smoothly!

About the volume: I am using [this](https://github.com/elenapan/dotfiles/blob/master/bin/volume-control.sh) script to control the volume. All you have to do is put it somewhere in your `$PATH` or call it using the full path.

I am closing this, if you have any issues you can reopen it.

**Comment by maxdevjs** [comment]
Just a comment: yes, volume control (and other things) did not work because I did not add your specific scripts. 

Thank you again for this :)
