### ISSUE TITLE
layout indicator appears off-center on lovelace

### ISSUE THREAD

**Issue by arsdragonfly** [elenapan/dotfiles#40]
![Imgur](https://i.imgur.com/6kEjS9q.png)

**Comment by elenapan** [comment]
It is just a scaling issue (probably our monitors have different dpi).

Can you try increasing the variable `theme.wibar_width` in `~/.config/awesome/themes/lovelace/theme.lua`?

**Comment by arsdragonfly** [comment]
yes, it helps. Perhaps calculating the width dynamically would prevent this issue and make the bar remain centered.

**Comment by elenapan** [comment]
It is not possible to calculate it exactly.

The icons are in square shape, their height is limited by the `theme.wibar_height` variable, thus their width is also equal to `theme.wibar_height`. There is a total of 12 icons in the bar, so their total width is `12 * theme.wibar_height`. However, the 2 gray separators (after the first icon and before the last icon) are created by printing the `|` character with a big font, so I do not know their exact width.

You can temporarily change the `theme.wibar_bg` to some other value, such as `"red"` just so you can easily eyeball different values of `theme.wibar_width` and knowing if the bar is too big or too small.

**Comment by elenapan** [comment]
Closing since I cannot do anything about it.
