### ISSUE TITLE
fontconfig dotfile not being applied correctly

### ISSUE THREAD

**Issue by Charly6596** [elenapan/dotfiles#41]
Hello, first of all, thank you for sharing this amazing work, it helped me a ton to get started with awesome!

I'm almost done with my setup, but I'm facing some issues with fonts, for example, this is how my vim lightline looks like:

![image](https://user-images.githubusercontent.com/13708100/62008019-e6428880-b154-11e9-9edc-e1999015924f.png)

Got the same issue with the bunnyfetch script

If I remove your lightline config it works just fine

My .Xresources file looks a bit weird, i assume it should look like yours
![image](https://user-images.githubusercontent.com/13708100/62010353-1cd6ce00-b16a-11e9-8537-6a2dfdc40916.png)

I already got a nerd font and typicons installed, I did a bit of research and found out the fontconfing isn't being applied correctly (placed the dotfile at ~/.config/fontconfig/fonts.conf), I suspect that's my issue, but I'm quite inexperienced with fonts:
```sh
~: fc-match monospace       
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
```
Any pointer will be really appreciated!
btw i use Arch!

**Comment by Charly6596** [comment]
Setted up locales and .Xresources is fine now, among with other things. Vim looks _righter_, still having issues with icons, now they show up as squares:
![image](https://user-images.githubusercontent.com/13708100/62012037-4818e780-b181-11e9-94c8-b8200590187e.png)
![image](https://user-images.githubusercontent.com/13708100/62012039-50712280-b181-11e9-8730-a36c2811eb94.png)

**Comment by elenapan** [comment]
Hello, 

It looks like you are using `urxvt`. I am also familiar with these boxes sadly, and I had to switch to a different terminal because of them. I have tried really hard in the past to make font icons to work in `urxvt` but it seems that if they are too wide, they are just displayed as boxes.

Could you try another terminal just to check if the fonts can be displayed correctly? I know for sure that `termite` does not have this issue.

PS about your first post: The `fontconfig` configuration file should not really affect any of the font icons. You could remove it if it creates any problems for you. It should only affect how crisp the fonts themselves look (by adjusting hinting, anti-aliasing, and other font rendering settings) and what fonts should be used by default as `monospace` and `sans`.

**Comment by Charly6596** [comment]
Yes, I'm using `urxvt`. For anyone ever having this issue here's what I did:
 
Switched to `xst` and some of the icons from the `bunnyfetch` weren't working (yet). I had the [nerd-fonts-complete (AUR)](https://aur.archlinux.org/packages/nerd-fonts-complete/) package, so tried to uninstall it and install only the one I wanted, [nerd-fonts-source-code-pro (AUR)](https://aur.archlinux.org/packages/nerd-fonts-source-code-pro/). That fixed the `bunnyfetch` icons issue.

To fix the vim lightline icons (zsh theme too), I had to take the icon codes from the [typicons webpage](https://www.s-ings.com/typicons/) and replace the icons myself.

To copy the icon and paste it somewhere else, I had to execute `echo -p <icon-code>` and copy the result, for example `echo -p  '\ue049'`
![image](https://user-images.githubusercontent.com/13708100/62014769-4234fd80-b1a5-11e9-93e3-1e00e9411eb1.png)

So everything seems to be working now, ready to play around with the themes myself! Sad about the `urxvt` issue thought. I can confirm `xst`, `termite` and `kitty` works with icons. 

Regarding to the `fontconfig`, the issue is still there, even thought I specified the font I want to use as `monospace` in the dotfile (just modified the font name in yours), I still get `DejaVu` font whenever I use monospace (or even `sans` and `serif`). But that's something I can deal with right now and might be an issue with my setup rather than with your dotfiles :man_shrugging: will update this issue if I ever fix it

**Comment by cybarspace** [comment]
In case someone comes looking and wants to know how `fontconfig` works, this may be helpful.
[`fontweak`](https://github.com/guoyunhe/fontweak) (font + tweak) is a nice GUI front-end for `fontconfig` and I fixed my own typicon issue with bunnyfetch using this, with the following setup.

![image](https://user-images.githubusercontent.com/50134239/106483616-edc8b780-64d8-11eb-9433-1ef84cf207a0.png)

PS: Your fonts can be different. Important thing is to have typicons at the end (or somewhere).
