### ISSUE TITLE
How do I connect music to spotify?

### ISSUE THREAD

**Issue by s0344** [elenapan/dotfiles#49]
Am I able to change mpd to spotify? since they are kinda different and idk what to change in the config.

**Comment by elenapan** [comment]
Hi there, sorry for the late reply, I have been super busy these days.

I implemented a spotify daemon similar to the mpd one. It emits signals only whenever spotify changes state and stays idle the rest of the time (and thus consumes no CPU). The repo is updated to include this daemon at `config/awesome/evil/spotify.lua`. 

An example widget that uses the daemon signals to update itself is at `config/awesome/noodle/spotify.lua`.

All you need to do is add `local spotify = require("noodle.spotify")` somewhere in `sidebar.lua` or `sidebar_v2.lua`, whichever you are using (the latest theme uses v2). And then put the widget somewhere in the sidebar items. I guess you can replace the `mpd_song,` line with `spotify,`.

Let me know if it works.

**Comment by s0344** [comment]
It works!!! Thank you so much!!! I have been trying to do it figure it out but failed. You made my day  :)

**Comment by s0344** [comment]
There is a bug.
It is showing two notification when it changes song.
I think one is from spotify and one is from the widget.

**Comment by elenapan** [comment]
Yes, you can keep whichever one you like. If you want to disable the widget notification you can do so in `~/.config/awesome/noodle/spotify.lua`

**Comment by s0344** [comment]
How do I disable Spotify's original notification?

**Comment by elenapan** [comment]
Probably through Spotify's settings.

**Comment by elenapan** [comment]
Found it: click the dropdown arrow at the top right, click settings, scroll to Display Options and untick the "Show desktop notifications when song changes" setting.

**Comment by s0344** [comment]
> Found it: click the dropdown arrow at the top right, click settings, scroll to Display Options and untick the "Show desktop notifications when song changes" setting.

Thanks, I found a dumb way of modifying the config file of spotify

**Comment by tjw0lf** [comment]
This is Awesome @elenapan i asked you on reddit about spotify you are Awesome GoD :D 

@s0344 can share how you did it id like to know. No why is dumb if it works for you :)

**Comment by s0344** [comment]
> This is Awesome @elenapan i asked you on reddit about spotify you are Awesome GoD :D
> 
> @s0344 can share how you did it id like to know. No why is dumb if it works for you :)

Do what @elenapan said, download the noodle/spotify.lua file then add it in sidebar.lua. Also, if you didn't update the entire dotfile because you have your own modifications, you have to download the evil/spotify.lua and add it to the evil/init.lua file.
