### ISSUE TITLE
rofi_mpvtube

### ISSUE THREAD

**Issue by calvin-evans** [elenapan/dotfiles#50]
Hey :wave: 

I noticed the refecnce in the app draw to "~/scr/Rofi/rofi_mpvtube" - any chance of adding it to the repo? More out of curiosity than anything :) 

Huge fan by the way :blush:

**Comment by elenapan** [comment]
Hi there, just added it in the `bin` folder. Enjoy :)

**Comment by calvin-evans** [comment]
thanks! :)
