### ISSUE TITLE
Titile bar not working with Chromium

### ISSUE THREAD

**Issue by s0344** [elenapan/dotfiles#53]
Sorry for that posting that many issues...
But as the following picture shown, the rounded edge and title bar is missing on chromium.
![2019 09 20-01 55 44 screenshot](https://user-images.githubusercontent.com/44009744/65302661-d8542700-db49-11e9-9508-b24029a2469c.png)

**Comment by elenapan** [comment]
They work for every window, but for some windows they are disabled.
In `rc.lua` look for `    -- Titlebars OFF (explicitly)` in the client rules and remove `"Chromium"` from the list.

**Comment by s0344** [comment]
Thanks, that fix it. 
I saw firefox and sublime text in the list too but my firefox and sublime text still have a titlebar, idk why it is working on Chromium but not these two...

**Comment by elenapan** [comment]
Some programs occasionally change their class names (kinda rare but Firefox did it recently when version 68 was released I think) so some of those rules might be outdated. You can find the class name of any window by using `xprop | grep -i class` and clicking on it. The first string corresponds to the `instance` and the second to the `class` property of AwesomeWM client rules.
