### ISSUE TITLE
screenrec.sh

### ISSUE THREAD

**Issue by BassMatt** [elenapan/dotfiles#55]
Hey Elena!

Back again using your dotfiles (on like my 5th setup).

Looking through you app drawer, there's the `record_command` which calls `screenrec.sh`.

Would you mind throwing that in the `bin` of scripts you use? I want to check it out (it would be super handy).

**Comment by paranoid73** [comment]
HI ,
you can use https://github.com/mtzanidakis/screenrec.sh

**Comment by elenapan** [comment]
It has been uploaded [here](https://github.com/elenapan/dotfiles/blob/master/bin/screenrec.sh).
