### ISSUE TITLE
Vim lightline unicode symbols

### ISSUE THREAD

**Issue by paradoxsurpeme** [elenapan/dotfiles#57]
Hi, it seems that I cant get lightline symbols to work correctly in vim 
![Screenshot_20190929_160041](https://user-images.githubusercontent.com/25790642/65832854-52b34280-e2d2-11e9-905c-87cc389e1d3a.png)

**Comment by paranoid73** [comment]
Hi @paradoxsurpeme , you need to provide details like , what do you use as font ? terminal ? ...

**Comment by paradoxsurpeme** [comment]
Hi @paranoid73 I use kitty terminal with fira code .When I open the file I can see the symbols as they should be : 
![image](https://user-images.githubusercontent.com/25790642/65833883-d32b7080-e2dd-11e9-95dc-67db63b04e9a.png)

**Comment by paranoid73** [comment]
here he use [monospace](https://github.com/elenapan/dotfiles/blob/3ed8ed2dff8ca6e81ad2ee1bb5d2ad9dcd6dc838/config/kitty/kitty.conf#L5) , check out

**Comment by elenapan** [comment]
You have to disable the lightline plugin and put `source ~/.config/nvim/statusline.vim` at the bottom of `init.vim`.

`statusline.vim` is a statusline configuration meant to be used without any plugins.

**Comment by paradoxsurpeme** [comment]
I see thanks a lot !
