### ISSUE TITLE
Ubuntu: attempt to concatenate a nil value(local 'fg')

### ISSUE THREAD

**Issue by hkyq** [elenapan/dotfiles#58]
Hey, I'm getting a notification about an error in awesome `attempt to concatenate a nil value(local 'fg')`, the same as #42. I am on Linux Mint and have Awesome 4.3. I've installed all the dependencies except `light` which I couldn't find. Also when switching WM's, the theme doesn't seem to be showing (I've only changed my `~/.config/awesome` though)

EDIT: Okay so I've compiled Awesome from source. I don't get the notifications anymore (or at least they aren't showing, I was getting a warning about notifications taking up the widget area) but only the bottom bar is themed, and the super key opens up the default Mint search menu.

**Comment by elenapan** [comment]
You need to build AwesomeWM from source. Version 4.3 does not include the new notification API, which I am using in this configuration.

If you have built it and installed it successfully, running `awesome -v` should print `awesome v4.3-xxx-yyyyyyyyy` and not only `awesome v.4.3`.

About `light`, it is not in Ubuntu's official repositories, but you can either build from source, or download their `.deb` file in the [releases](https://github.com/haikarainen/light/releases/) page. You can install `.deb` files with `sudo dpkg -i something.deb`

**Comment by elenapan** [comment]
Sorry, just saw your edit.

I think your Mint/Cinnamon desktop is somehow capturing the super key when X server starts, even though you are logged in with Awesome. Not really sure how to troubleshoot this, apart from unbinding the key in your desktop settings. However there might be other overlapping keys, so maybe it is not the best solution to unbind them all.

Also, what do you mean with only the bottom bar is themed? What about the windows, sidebar? You can send a screenshot if you like.

**Comment by hkyq** [comment]
![GIF](https://user-images.githubusercontent.com/20865218/66205140-9ca57b00-e67a-11e9-879e-718300c30245.gif) (First I press the super key, then I click the bottom left icon). 

Also I noticed when I was copying the config files, I overwrote mine with yours if they existed. It's a fresh install in a VM so I don't think it really matters.

**Comment by hkyq** [comment]
I am moving to plain Ubuntu. Having some issues so might open a different Issue.

**Comment by Hkyx** [comment]
Hi @elenapan,

Got same problem on Manjaro, so want to try by building awesomewm myself instead of the aur repo.
If I check the official github, I saw 4.3 version only what steps did you took to build it for latest minor ? https://github.com/awesomeWM/awesome/tags 
or the code is already merged into the master ? didn't saw info about that

ty, Hk

@hkyq not far from your nickname ;)
