### ISSUE TITLE
Custom keybindings doesn't work

### ISSUE THREAD

**Issue by PandaFoss** [elenapan/dotfiles#59]
I have successfully installed the dotfiles in Arch Linux, but I have problems setting some keybindings. I have added the following lines in the `keys.lua` file, just below the function `keys.globalkeys = gears.table.join`:

```
awful.key({modkey, shiftkey}, "t", function() awful.util.spawn("telegram-desktop",false) end),
awful.key({modkey, shiftkey}, "w", function() awful.util.spawn("firefox",false) end),
```

The `Shift + Super + t` combination was already in use, so I changed `Shift` to `Alt`. I have restarted `awesome` and also tried restarting the PC, and nothing happens. I don't know how to debut it. I hope you can help me.

By the way, as I told you in Reddit, excellent work. Maybe i can contribute by creating a script that makes installation even easier. If you like the idea, as soon as I have some time I will start it.

**Comment by elenapan** [comment]
Hi there,
In the default AwesomeWM configuration, `modkey` is a variable that either represents your Super key (Win key) or Alt key. I have completely removed the `modkey` variable and instead use `superkey`, `altkey`, `shiftkey` and `ctrlkey`.
Simply change `modkey` to `superkey` and it should work.

You can open a separate issue for discussing the installation script.

**Comment by PandaFoss** [comment]
Oh, it was simple. Thank you!
