### ISSUE TITLE
Config breaks on startupt

### ISSUE THREAD

**Issue by darovit** [elenapan/dotfiles#60]
I followed the directions and installed all dependencies but when I try to launch awesome it gives the errors shown in the attached image and reverts to default config

https://imgur.com/OFLrCNP

**Comment by coderkalyan** [comment]
I'm having the same issue. I just installed tried installing this config set but it errors out. I've tried reverting a few commits backwards but nothing seems to change. I am running Arch Linux, and I believe I have all the dependencies installed.

**Comment by elenapan** [comment]
Hi guys,

In the dependencies I have `awesome (git master branch)` which means you need to build AwesomeWM from source. Version 4.3 does not include the new notification API which I am using in this configuration.

Arch users can easily install it with `awesome-git` from AUR. Other users need to follow the build instructions in [awesome's github page](https://github.com/awesomeWM/awesome/).

If you have built it and installed it successfully, running `awesome -v` should print `awesome v4.3-xxx-yyyyyyyyy` and not only `awesome v.4.3`.

**Comment by darovit** [comment]
To quote a wise philosopher: "I ain't the sharpest tool in the shed"

I uninstalled awesome and installed awesome-git and it unbroken everything. I'm still having an issue with the icons but I'm 99.9999% certain that's entirely my fault and I can fix it. Thank you so much!

**Comment by mostafahussein** [comment]
@darovit just ensure that you installed all the icons that was mentioned in the readme file and update it using `fc-cache` and restart awesomewm and it will show as expected

**Comment by elenapan** [comment]
Closing as the original issue is resolved. If you still have issues with the icons you may open a new issue.
