### ISSUE TITLE
[Idea] bars inside notifications

### ISSUE THREAD

**Issue by calvin-evans** [elenapan/dotfiles#62]
I know this isn't an issue - just thought you might be interested. Using conect_signal with your evil/x stuff like you have in the sidebar also works really nicely IMO inside a notification when changing brightness and volume - check it out :)

![bars](https://user-images.githubusercontent.com/1681236/66928310-151c1c80-f029-11e9-814d-ff53fde3f859.gif)

**Comment by elenapan** [comment]
Thank you, that is indeed a nice idea!
