### ISSUE TITLE
No titlebars and gear error when opening an application

### ISSUE THREAD

**Issue by pitems** [elenapan/dotfiles#63]
So just a few days ago i downloaded this amazing theme and also downloaded all dependencies listed on the github page, but for some reason all themes show me no titlebar whatsoever and a notification saying an error in gears/object/properties.lua -184 assertion failed. Aside from the titlebars and the notification error everything is fine, currently using archlinux. And awesome git 4.3-505
![2019 10 23-09 49 31 screenshot](https://user-images.githubusercontent.com/19554342/67394409-848a9280-f57a-11e9-9596-3aa427915742.png)

**Comment by elenapan** [comment]
Hi there,

I also have this problem after updating to the latest awesome git.
Another person reported the same problem here: https://github.com/awesomeWM/awesome/issues/2915

Until it gets fixed, I suggest using an older commit of awesome git.

I am looking into it as it might be my config that is causing the error.

**Comment by hrqmonteiro** [comment]
Did this, the close button is strange now, any tips? I would appreciate very much!

![2019 10 23-19 24 20 screenshot](https://user-images.githubusercontent.com/17055027/67438761-b75c7700-f5ca-11e9-9405-b73ae0de7f89.png)

**Comment by elenapan** [comment]
The close button is using the heart symbol from Material Fonts. I have a link to the font [here](https://www.dropbox.com/s/4fevs095ho7xtf9/material-design-icons.ttf?dl=0). Install it and it should be fixed.

**Comment by pitems** [comment]
i will try using an older version but sadly i don't know where to get it to try it out , somebody knows where i can get an older version of it??

**Comment by elenapan** [comment]
[Here](https://github.com/awesomeWM/awesome/commits/master) you can find all the older versions. Pick one and click the rightmost button which says "Browse the repository at this point in history". Then download that version and build as usual.

**Comment by pitems** [comment]
so i went back to a version from a month ago and now its working again (i tried the commit from the last day of september) thanks a lot for the help

**Comment by Elv13** [comment]
Anyone has the full backtrace for this?

**Comment by Elv13** [comment]
Actually it was something else.

```lua
-- Padding
-- Only visible when equal padding is desired for the client
{
    visible = user.anti_aliasing and equal_padding or only_borders,
    buttons = user.anti_aliasing and only_borders and buttons,
    bg = anti_aliasing_padding_color,
    forced_height = anti_aliasing_padding,
    widget = wibox.container.background
},
```

If I do:

    print("\n\n\n\nHAS BUTTONS", user.anti_aliasing, only_borders, buttons, user.anti_aliasing and only_borders and buttons)

Then the result is `false` instead of `nil`. Because `true and false and {}` evaluates to a boolean, not "table or nil" like you might expect when using the `or` operator to do `thing_a or thing_b or thing_c`.

So the old code was silently rejecting the boolean buttons while the new code acts like most of Awesome and assume the type is right or let it print the error popup (and/or exception handler).

**Comment by elenapan** [comment]
Thank you @Elv13 for the detailed explanation and for spending your time solving this. It was an easy fix thanks to your help.
```lua
    buttons = user.anti_aliasing and only_borders and buttons or nil,
```
@pitems @hrqmonteiro I pushed the fix. You guys can use the config with the latest Awesome.
