### ISSUE TITLE
Theme with classic app menu

### ISSUE THREAD

**Issue by PandaFoss** [elenapan/dotfiles#64]
Hello again! I do not know if I have searched correctly but as far as I have seen any of the themes I have an application menu like the one AwesomeWM brings by default. I am about to install Linux on a computer that is used by people with little experience in Linux and so on, so I would like a menu of applications like the Whisker Menu in XFCE desktop environment. I don't know if it is possible to edit any of your themes in any way so that this is possible. However, it may be a good idea for a future theme (if there is one).
Greeting and apologies for the inconveniences!

**Comment by elenapan** [comment]
Hi there,

Your best bet is to install `xfce4-appfinder` and bind it to some key and/or make a button which spawns it on click.

You can also use `rofi -show drun` with icons enabled. I think you will need the `git` version of rofi for icons to work.

If you want a native AwesomeWM application menu, you can either use `menubar` which is most similar to `rofi -show drun` but does not support clicking, or the menu that appears when right clicking the desktop.
You can test these 2 in the default AwesomeWM config, as I have removed them from mine.

**Comment by PandaFoss** [comment]
Thank you very much, I will try that. I close the issue.
