### ISSUE TITLE
Updated nvim config?

### ISSUE THREAD

**Issue by cbrasser** [elenapan/dotfiles#65]
From what I've seen the neovim configuration files in the repo is not the config shown in the newest screenshots, I'd be especially interested in the updated statusline config.

**Comment by elenapan** [comment]
The statusline config was uploaded [in a separate file](https://github.com/elenapan/dotfiles/blob/master/config/nvim/statusline.vim), you only have to source it in your own config and disable other statusline plugins you may have (Lightline, Airline etc).

**Comment by cbrasser** [comment]
Uh I'm a dummy, I sourced the file but overwrote it through Airline. Thanks for the quick response. If I may ask: In which font are the symbols contained (e.g. the start on the left side on your screenshot)

**Comment by elenapan** [comment]
The round symbols should be included in any Powerline font or Nerd Font. But if you are using `kitty` terminal, you do not need those fonts since the terminal can draw most powerline symbols natively.

**Comment by elenapan** [comment]
Closing, if your issue is still not resolved, let me know.

**Comment by williamJmelton** [comment]
I went as far as to literally copy the statusline.vim script into the bottom of my init.vim, and I don't see any changes in the lightline?

**Comment by elenapan** [comment]
It is not a lightline theme. Please disable your lightline plugin.
