### ISSUE TITLE
Using a command to show lock screen

### ISSUE THREAD

**Issue by fernedingd** [elenapan/dotfiles#69]
Is there any way to start your lock screen with a bash command? I'd like to add a routine for locking and suspending Awesome when it has been inactive for some minutes with xautolock, but i need to be able to call the lock screen like a program to do this.

**Comment by elenapan** [comment]
You can use `awesome-client "lock_screen_show()"`

**Comment by fernedingd** [comment]
Works like a charm. Thank you very much
