### ISSUE TITLE
Rofi does not Spawn with Super+D

### ISSUE THREAD

**Issue by adimishra1** [elenapan/dotfiles#78]
After following the exact same steps for installing in Arch Linux Rofi does not spawn with Super+D. While it works when I open it from the terminal.

**Comment by elenapan** [comment]
Please try the following debugging steps:

1. Check if this exact command works on the terminal:
    ```shell
    rofi -matching fuzzy -show combi
    ```

2. Check if any errors are printed when spawning rofi from inside AwesomeWM:
    Run this in your terminal. It will either launch rofi or print an error in a notification. Let me know what happens.

    ```shell
    awesome-client '
    local awful = require("awful")
    local naughty = require("naughty")
    awful.spawn.easy_async_with_shell("rofi -matching fuzzy -show combi", function(_, err, _, exit_code)
        if exit_code ~= 0 then
            naughty.notification({ title = "The error was:", message = err })
        end
    end)
    '
    ```

3. If step 2 worked without errors, then the issue might be input related. Try creating a notification inside the <kbd>super + d</kbd> keybind function:

    https://github.com/elenapan/dotfiles/blob/06458c76a299a5e1dad85241a0c5a5891f5ee9ae/config/awesome/keys.lua#L328-L332

    Add the line
    ```
    naughty.notification({ title = "super+d was pressed" })
    ```
    right before the `awful.spawn` command. Then restart awesome and press the keybind again.

**Comment by adimishra1** [comment]
1) Was working fine.
2) Gave an error that my Locale was not set, hence the error.


After setting the Locale it worked.
Also, do we have to install any dock? [https://camo.githubusercontent.com/87911b0e834b5a65615132baee3b00fa17ca624e/68747470733a2f2f692e726564642e69742f676c7a726b6b383366343632312e706e67](Here) in the 1st and 2nd screenshot there is a dock in the bottom.

**Comment by elenapan** [comment]
Sorry that link is broken so I can't see which screenshots you are referring to.

**Comment by adimishra1** [comment]
Link : https://camo.githubusercontent.com/87911b0e834b5a65615132baee3b00fa17ca624e/68747470733a2f2f692e726564642e69742f676c7a726b6b383366343632312e706e67

**Comment by elenapan** [comment]
In order to get that bottom bar all you need to do is change the bar theme to "lovelace" and the icon theme to "linebit". You can change both of them here:
https://github.com/elenapan/dotfiles/blob/06458c76a299a5e1dad85241a0c5a5891f5ee9ae/config/awesome/rc.lua#L31-L46

**Comment by adimishra1** [comment]
Yes, that worked. Thanks.
