### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by adimishra1** [elenapan/dotfiles#79]
Where are the screenshots stored?

**Comment by elenapan** [comment]
In the directory you can specify here:
https://github.com/elenapan/dotfiles/blob/06458c76a299a5e1dad85241a0c5a5891f5ee9ae/config/awesome/rc.lua#L82-L84

Make sure it exists or screenshots will be lost.

**Comment by adimishra1** [comment]
Ok Yes Got It.

**Comment by ejuarezg** [comment]
I ran into the issue where I left off the forward slash (/) at the end of the variable and the screenshots saved with a different name. Just thought I let you avoid this problem by including the slash.
