### ISSUE TITLE
Weather widget not showing information

### ISSUE THREAD

**Issue by Zander-Labuschagne** [elenapan/dotfiles#8]
Hello,

Thank you for publishing this _awesome_ dotfiles, you are the reason I switched from KDE to awesome WM (I am completely new to awesome and lua). I have created an account at OpenWeather and added my API key and my city code. It only shows the whatever.png icon and a "C" next to it. I did execute the API call inside the terminal to see if it returns data. I have received the following: 
`{"coord":{"lon":27.1,"lat":-26.72},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"base":"stations","main":{"temp":29.9,"pressure":870.23,"humidity":38,"temp_min":29.9,"temp_max":29.9,"sea_level":1015.78,"grnd_level":870.23},"wind":{"speed":3.85,"deg":307.503},"clouds":{"all":48},"dt":1547040716,"sys":{"message":0.0191,"country":"ZA","sunrise":1547004447,"sunset":1547053796},"id":964349,"name":"Potchefstroom","cod":200}% `

It is as if the `01d`, `01n` etc. could not be found in `weather_details` in the weather.lua script. Can you maybe give me an idea of why this should happen? (ps. this is my first issue ever, let me know if I did anything wrong)

**Comment by elenapan** [comment]
Hello there. 
Since the API call returns the data, I am thinking there could be an issue with the script trying to extract the data. Do you have `jq` installed? The script uses it to extract data from the JSON that is returned through the API call.
In order to test if it works or not you could make a file, copy paste the script in it, fill in your key and city id, and make it executable.

    #!/bin/bash
    KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    CITY="yyyyyy"
    UNITS="metric"
    SYMBOL="°C"
    
    weather=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$KEY&id=$CITY&units=$UNITS")
    
    if [ ! -z "$weather" ]; then
        weather_temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
        weather_icon=$(echo "$weather" | jq -r ".weather[].icon" | head -1)
        weather_description=$(echo "$weather" | jq -r ".weather[].description" | head -1)
    
        echo "$weather_icon" "$weather_description" "$weather_temp$SYMBOL"
    else
        echo "... Info unavailable"
    fi

Then run it in your terminal and inform me of any errors that come up.
Successful output should be something like `13n light snow 0°C`.

**Comment by Zander-Labuschagne** [comment]
whohoo! Thank you, it was jq not being installed, so I installed it, it is working fine now. Just to be complete, the errors the script gave was:  jq: command not found in lines 10 through 12. Thank you very much! Your dotfiles are much appreciated :)

**Comment by elenapan** [comment]
You are very much welcome :)

**Comment by abeljim** [comment]
Hello I am having a similar problem but the script above just fine for me. I just get info unavailable. Any guess on where it could have failed?
