### ISSUE TITLE
Error with Gimp

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#81]
![2020 05 10-21 00 58 screenshot](https://user-images.githubusercontent.com/17055027/81513812-99faba80-931a-11ea-99fb-5d82190bc750.png)

Everytime i open gimp or any window inside gimp it notifies me this error.
I'm not an expert or anything so i hope someone can help me. With other awesome configs or other WMs this error don't happen. Any help?

**Comment by elenapan** [comment]
Hi there,

Is the issue closed because it is solved?

I cannot reproduce it on the latest AwesomeWM: https://github.com/awesomeWM/awesome/commit/c10b4e4b1075bdcf6f4e81539543b431ccba2381

- What is the output of `awesome -v`?

- Are you using multiple monitors?

- Does this change solve the issue?
```diff
diff --git a/config/awesome/rc.lua b/config/awesome/rc.lua
index a6a2877..7cc3bc2 100644
--- a/config/awesome/rc.lua
+++ b/config/awesome/rc.lua
@@ -759,7 +759,6 @@ awful.rules.rules = {
     {
         rule_any = {
             class = {
-                "Gimp",
                 "Inkscape",
             },
         },
```
