### ISSUE TITLE
Cannot resize windows

### ISSUE THREAD

**Issue by sueperb** [elenapan/dotfiles#88]
I may be missing something key here, but you cannot resize windows (for example make them half screen)

Sorry if I've missed something obvious

**Comment by elenapan** [comment]
The default layout for most workspaces is "maximized".
This means that all windows (with some exceptions) take up the whole screen and are stacked on top of each other.

You can press `super+s` to enable tiling mode for the selected workspace or you can press `super+shift+s` to enable floating mode.

This will only last until you restart AwesomeWM.
You can permanently change the default layout for each workspace here:

https://github.com/elenapan/dotfiles/blob/091fca68047fa3d7e9952464d6832af6d0ff5b39/config/awesome/rc.lua#L279-L291

**Comment by sueperb** [comment]
thanks
