### ISSUE TITLE
AwesomeWM stack traceback error on start up 

### ISSUE THREAD

**Issue by P1nkBug** [elenapan/dotfiles#91]
Hey!
AwesomeWM threw an error on first log in 

`Oops, there were errors during startup!
error while running function!
stack traceback:
    /home/pinkbug/.config/awesome/rc.lua:165: in main chunk
error: /home/pinkbug/.config/awesome/rc.lua:165:attempt to call a nil value (field 'connect_signal').`

I found the same error on a reddit post from about 3 months ago (https://www.reddit.com/r/awesomewm/comments/fsh03s/stack_traceback_error_on_start_up/)
kinda a newbie so any help is much appreciated :) Awesome work btw!!

**Comment by P1nkBug** [comment]
Also when I log in with AwesomeWM there is pretty much nothing there, no icons,apps,menus  or any of the other conifs just the vanilla AwesomeWM black wallapaper and the error message, is this caused by the error I described or did I mess something else up in the configuration?

**Comment by ceuk** [comment]
You're using a version of AwesomeWM that's too old. Make sure you install 
the latest version from git. Check out the instructions here: 
https://github.com/awesomeWM/awesome/#building-and-installation

**Comment by P1nkBug** [comment]
Thanks for the quick reply @ceuk !!
Ended up running into more problems and I don't think I have the courage to troubleshoot anymore maybe I'll give this set up another try in the future. Thanks for your help
