### ISSUE TITLE
Hide wibars command

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#95]
Hi, i don't want to bother again, but is the hide bars command (default keys: super + shift + b) working on this new config? (I now the amarena config has a autohide bar, but i'm using the ephemeral bar theme). I just want to know if it is just here, but not working here.

Thanks in advance.

**Comment by elenapan** [comment]
Hi there.

I changed that bind to <kbd>super + b</kbd> since it is was not used and it is easier to press. The README was updated.

You can of course change this bind in `keys.lua` if you like.
