### ISSUE TITLE
Amarena bar not working properly

### ISSUE THREAD

**Issue by Zander-Labuschagne** [elenapan/dotfiles#97]
When choosing to use the Amarena bar it is hidden by default, when I use `super + b` to show it, it removes a piece if my active window but shows my wallpaper in its place(see attached screenshot). Anyone else having this problem? I feel like I'm the only one who is having this problem. Or am I confusing the bar at the top(tag selector) with the bottom one? I would like to have the bar shown at the bottom of the first screenshot in the Amarena theme. I am no expert in Lua or AwesomeWM, just leeching off of Elena's gorgeous work. Is the bar at the bottom a tag selector like the one from the famous Lovelace theme?
![image](https://user-images.githubusercontent.com/22447350/87816169-2e2b5580-c867-11ea-9fc5-1a34512b1ba3.png)

**Comment by ceuk** [comment]
Hey, sounds like Compton/Picom isn't working.

Check it's running (`ps aux | grep picom\|compton`) and start it if not.

**Comment by Zander-Labuschagne** [comment]
Yeah it wasn't running thanks, it was supposed to run by itself on startup, guess I'll have to check that again. Now the bar is just invisible, I can see the mouse pointer changing into a hand when I move over the bar but I see whatever would be behind the bar, in the case of the screenshot it would be Sublime Text.

**Comment by elenapan** [comment]
Hmm that is strange. Have you loaded a colorscheme through your `~/.Xresources` or by running `xrdb -merge /path/to/colorscheme`?

**Comment by Zander-Labuschagne** [comment]
I had a colourscheme defined in my .`~/.Xresources` but just in case I made a backup and replaced the whole file with yours, and did `xrdb -merge /.xfiles/amarena` followed by restarting awesome.

**Comment by ceuk** [comment]
Could be the icons, you definitely got the icons folder in ~/.config/awesome?

Failing that you could see if there's any errors in xorg-session.log

**Comment by Zander-Labuschagne** [comment]
Yes I have, I also copied a fresh copy from the repo and restarted awesome. I did add icons for apps I use which I added to the app drawer, but I think I will restart from scratch and clone everything as is because I have a feeling I might have messed something up. 

Where exactly is `xorg-session.log`? The best I could find is the following output from `cat .local/share/xorg/Xorg.0.log | grep error`:
```
(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  7845.260] (WW) xf86CloseConsole: KDSETMODE failed: Input/output error
[  7845.260] (WW) xf86CloseConsole: VT_GETMODE failed: Input/output error
[  7845.260] (WW) xf86CloseConsole: VT_ACTIVATE failed: Input/output error`
```
which looks unrelated but I'm not an expert.

**Comment by elenapan** [comment]
I am starting to think this is more of a GPU or driver issue.
What is your GPU? Also, is this inside a VM?

I have a few suggestions to try. Let me know if any of them make any difference.

1. Try each one of these commands to run `picom`:
    - `picom --backend glx --config /dev/null`
    - `picom --backend xrender --config /dev/null`
    - `picom --experimental-backends --config /dev/null`
2. Temporarily install `xcompmgr`, kill `picom`, and run `xcompmgr` instead.
3. Temporarily make this change and restart Awesome.

   ```diff
   diff --git a/config/awesome/elemental/bar/amarena.lua b/config/awesome/elemental/bar/amarena.lua
   index 9138b80..d612b6f 100644
   --- a/config/awesome/elemental/bar/amarena.lua
   +++ b/config/awesome/elemental/bar/amarena.lua
   @@ -116,7 +116,7 @@ awful.screen.connect_for_each_screen(function(s)
        s.dock = awful.popup({
            -- Size is dynamic, no need to set it here
            visible = false,
   -        bg = "#00000000",
   +        bg = "#666",
            ontop = true,
            type = "dock",
            placement = dock_placement,
   ```

**Comment by Zander-Labuschagne** [comment]
No not a VM, GPU is Intel Corporation HD Graphics 620 (rev 02) on a Dell XPS 13 laptop.  After the change to the bar file the following in the screenshot can be observed. Note the orange line near the top below the tag selector and the gray dock bar. The other changes had no effect.x-special/nautilus-clipboard
copy.
![Screenshot_2020-07-18_14-03-48](https://user-images.githubusercontent.com/22447350/87852176-f2909a00-c8ff-11ea-817a-bfd72b65a815.png)
That orange line is not always in the same place, it now moved more to the right. This seems to be a weird problem, I don't mid rather using the lovelace bar instead if we cannot solve this problem.

**Comment by elenapan** [comment]
I see.

- Do other semi-transparent widgets like the dashboard (<kbd>super + F1</kbd>) look alright?

- What about the new window switcher (<kbd>super + tab</kbd>)?

- How do you set your wallpaper?

    Is it with `feh --bg-fill /path/to/wallpaper` or are you using AwesomeWM's built in wallpaper setting method?

- Could you temporarily try this change?

```diff
diff --git a/config/awesome/noodle/dock.lua b/config/awesome/noodle/dock.lua
index 782ed10..55f6830 100644
--- a/config/awesome/noodle/dock.lua
+++ b/config/awesome/noodle/dock.lua
@@ -14,7 +14,7 @@ local class_icons = icons.text.by_class
 local item_font = "icomoon 15"
 local item_bg = x.background
 local item_size = dpi(50)
-local item_shape = helpers.squircle(1.7, 0)
+local item_shape = helpers.rrect(dpi(8))
 local item_margin = dpi(8) -- For spacing between items
 local indicator_spacing = dpi(8)
 local indicator_height = dpi(7)
```

Sadly, it is hard to fix this as I cannot reproduce it and have never seen it before.

**Comment by Zander-Labuschagne** [comment]
Yes the dashboard and window switcher works fine.

I set my wallpaper using `feh --bg-max /path/to/wallpaper` from shell script in my `/usr/bin/` directory (it also fetches a wallpaper from reddit) which is called from `.profile` in my home directory.

Oh wow that change made it work, thank you, I just need to revert the background colour.
![Screenshot_bar](https://user-images.githubusercontent.com/22447350/88172293-09e1c700-cc21-11ea-8709-a1e3a6c4bb7a.png)

I understand the difficulty of not being able to reproduce a behavior, I am a software developer and I do get the occasional bug report from testing that I can't reproduce. I just need to spend more time on a regular basis with AwesomeWM dotfiles to get more acquainted with it and Lua. Thank you for your help and efforts, and thanks to ceuk as well.

**Comment by ceuk** [comment]
Oh that's so annoying, I actually had that exact issue when I was trying the bar out. I just completely forgot.

Turns out the "squircle" shape is pretty new so I just needed to rebuild my AwesomeWM from the latest git files. If you want to stay in sync with this repo you could try updating awesome and setting if that fixes it for you too

**Comment by Zander-Labuschagne** [comment]
Great thanks ceuk. Now I'm wondering, how does the AUR helper decide when to update a git package? Do the maintainer flag it on the AUR?

An off-topic question, I added a **glow** effect to the linebit icons when hovering on them in the exit screen and in my app drawer, should I make a PR? The reasons I never did was because I've added additional icons for the apps I use and not everyone wants those icons and I also have changed many things on my side that deviated from the vanilla themes, e.g. I use lovelace exit screen with font/text from ephemeral and app drawer with linebit icons. And I also don't know what I'm doing so my code is a mess, I just know how to read and copy paste from existing code.

**Comment by elenapan** [comment]
> ... how does the AUR helper decide when to update a git package?

You can force it to check for development package updates.
For example, if you are using `yay`:
```shell
yay -Syu --devel --timeupdate
```

However, the last commit was about 17 days ago, so you are probably up to date and the issue could actually be a bug in the `squircle` shape.

If you have time, could you please try something like this?
```diff
-local item_shape = helpers.squircle(1.7, 0)
+local item_shape = helpers.squircle(1.7, 0.01)
```

If the icons still do not show up, keep increasing `0.01` by small increments until they do.

---

As for the pull request, I am not sure if I would merge it.
The reason is that whenever I add new icon themes, I would also have to create a "hover" version of them as well. 
I am glad your solution works for you however :)

**Comment by Zander-Labuschagne** [comment]
My awesome build was behind and I have updated it and the `squircle` seems to work now. 

I understand, I was(and still) wondering if I should replace them with the text/unicode icons to make my life easier but I like the linebit icons more, I just need to find/create ones for my IDE's because they currently don't fit the theme.

**Comment by elenapan** [comment]
Good to know it works now.

About the icons, have you tried the [Sweet icon](https://www.gnome-look.org/p/1305251/) theme? It was made specifically for the Linux desktop (unlike Linebit, which was made for mobile apps) so you could grab some icons from there. If not, what I would do is find a generic "editor" icon, and recolor it with different accent colors for every editor/IDE.

**Comment by Zander-Labuschagne** [comment]
Thanks, they look more fitting.
