### ISSUE TITLE
Titlebars, thunar etc

### ISSUE THREAD

**Issue by Seyeumi** [elenapan/dotfiles#98]
Hi again ! 

Trying to use the newest update and I've ran into a few issues

1. The bottom bar / dock disappears even if I have it enabled with super + b, or I've misunderstood something. Another issue I have come across is that while clicking on the firefox icon opens firefox, it still gets placed as a new entry ( [image](https://imgur.com/fGVBPHg) )

2. Is it possible to make sure that things like firefox spawns without titlebar instead of having to toggle it with super + t ? I think I read it somewhere so forgive me for being lazy :( 

3. I'm wondering what your thunar file manager looks like, I don't think you've shown it. I don't think anything is wrong but I wanna make sure, hehe.

4. Another interesting thing is the sidebar looks a little different on [1920x1080](https://imgur.com/tFzKbL8) , I'm assuming it's just because of the resolution, it still fully functions

5. Is there a way to make thunar open kitty instead of the other terminal with the "open terminal here"

6. When using the new, very cool, window switcher it skips out over minimized windows I believe, is it possible to make it just go through them all?

Sorry for all these questions :(

I just wanna say thank you for getting me into linux, your posts inspired me to really try it out !

**Comment by elenapan** [comment]
Hi there, sorry for the late answer.

1. <kbd>super + b</kbd> toggles the visibility but does not toggle the autohide functionality. So it should disappear if you move your mouse out of it. Let me know if you want to change this, I can provide some help.

   About Firefox: I have noticed that Firefox has a different window `class` across distros. You can get the `class` of Firefox by running `xprop WM_CLASS` in your terminal and clicking the Firefox window.
   
   It will print something like this. We need the second string:
   
   ```
   WM_CLASS(STRING) = "Navigator", "firefox"
                                       ^
                                    this one
   ```
   
   Careful, It is case sensitive.
   
   Then change the current firefox `class` in the dock's pinned classes to the one you got from `xprop`. You will only need to fix lines 55 and 63:
   
   https://github.com/elenapan/dotfiles/blob/4493396bc7884a5fc318a49f6a33e81e75f998ec/config/awesome/noodle/dock.lua#L54-L67


2. Same Firefox issue as above. I have already set Firefox to launch without titlebars in `rc.lua`. All you need to do is add your Firefox's `class` to that list, inside the `class` block at line 500.

   https://github.com/elenapan/dotfiles/blob/4493396bc7884a5fc318a49f6a33e81e75f998ec/config/awesome/rc.lua#L486-L501

3. I actually do not even have Thunar installed anymore.

   I simply use the terminal to move files around, and occasionally I use ranger if I want file previews. This is how it looks, using the [ranger_devicons plugin](https://github.com/alexanderjeurissen/ranger_devicons):

    
   ![image](https://user-images.githubusercontent.com/31134749/88102130-baab8000-cba7-11ea-881a-c7c65cf51bbc.png)


   I use a slightly modified version of Luke Smith's [dmenumount](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenumount) and [dmenuumount](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenuumount) for mounting drives.

4. My resolution (3840x2160) and yours (1920x1080) are both 16:9 so this difference can't be right. Could you show a screenshot of the whole desktop with the sidebar open? I am thinking it could be a DPI issue.

5. You can run `exo-preferred-applications`, go to `Utilities` tab and pick your preferred terminal emulator. If it is not there, you can pick `Other` and type the full path to it. Get the full path by running `which <your-terminal>`, for example `which kitty`. It should print something like `/usr/bin/kitty`.

6. This might require quite a few changes to the window switcher code to be possible. I will be a bit busy these days so I will get back to you soon about this. Please leave this issue open in the meantime.

**Comment by Seyeumi** [comment]
Thank you very much for the quick and amazing help !!
My preference would be to have the bar there at all times or toggling the autohide, I will try and figure it out myself, think and hope I can do that at least haha.

[Fullscreen image of sidebar](https://imgur.com/a/sCEkG5w)

It could be a DPI issue I've played around with it trying to find a good spot where things are the right size for me but sadly it's just my laptop.

All the other issues have been fixed thank you so much, no need to hurry or anything I don't need to fix these things, it's just something a little nice.

Thank you Elena

**Comment by elenapan** [comment]
Hi there,

Small update:
I managed to make it so that the window switcher can cycle between both unminimized and minimized windows with minimal changes to the code.

I am quite liking how it works so I decided to keep it (commit 0c33554).

Let me know if you find any issues with it.

---

Finally, let me know if you still need help with the dock changes you wanted to make.

**Comment by Seyeumi** [comment]
I think I am all good now!
Thank you very much Elena, hope you're having a nice day

I'll close this now as well
